// PART 1 of translations - products 1-50
// This file will be merged into the main products.js
window.PRODUCT_TRANSLATIONS = window.PRODUCT_TRANSLATIONS || {};
Object.assign(window.PRODUCT_TRANSLATIONS, {
  1: {
    en: { hook: "Carved plum wood.", desc: "Circa 1950. Carved plum wood.\n50 x 68 x 5 cm.\nAnthroposophic frame in plum wood." },
    fr: { hook: "Bois de prunier sculpté.", desc: "Vers 1950. Bois de prunier sculpté.\n50 x 68 x 5 cm.\nCadre anthroposophique en bois de prunier." },
    it: { hook: "Legno di susino intagliato.", desc: "Circa 1950. Legno di susino intagliato.\n50 x 68 x 5 cm.\nCornice antroposofica in legno di susino." }
  },
  2: {
    en: { hook: "After Rudolf Steiner, Dornach / Basel.", desc: "After Rudolf Steiner, Dornach / Basel.\n175 x 230 x 38 cm.\n145 x 83 (115) x 38 cm.\nAnthroposophic corner sideboard after Rudolf Steiner, Dornach / Basel." },
    fr: { hook: "D'après Rudolf Steiner, Dornach / Bâle.", desc: "D'après Rudolf Steiner, Dornach / Bâle.\n175 x 230 x 38 cm.\n145 x 83 (115) x 38 cm.\nMeuble d'angle anthroposophique d'après Rudolf Steiner, Dornach / Bâle." },
    it: { hook: "Da Rudolf Steiner, Dornach / Basilea.", desc: "Da Rudolf Steiner, Dornach / Basilea.\n175 x 230 x 38 cm.\n145 x 83 (115) x 38 cm.\nMobile angolare antroposofico da Rudolf Steiner, Dornach / Basilea." }
  },
  3: {
    en: { hook: "A pair of Italian table lamps, circa 1950.", desc: "A pair of Italian table lamps, circa 1950. Glass and metal, painted green and red.\nH = 53 cm each." },
    fr: { hook: "Une paire de lampes de table italiennes, vers 1950.", desc: "Une paire de lampes de table italiennes, vers 1950. Verre et métal, peints en vert et rouge.\nH = 53 cm chacune." },
    it: { hook: "Una coppia di lampade da tavolo italiane, circa 1950.", desc: "Una coppia di lampade da tavolo italiane, circa 1950. Vetro e metallo, verniciati in verde e rosso.\nH = 53 cm ciascuna." }
  },
  4: {
    en: { hook: "Switzerland, probably Zurich, 17th/18th century.", desc: "Switzerland, probably Zurich, 17th/18th century. Bell casting. Round form on three legs. Domed lid with disc knob.\n16 x 16 cm." },
    fr: { hook: "Suisse, probablement Zurich, XVIIe/XVIIIe siècle.", desc: "Suisse, probablement Zurich, XVIIe/XVIIIe siècle. Fonte de cloche. Forme ronde sur trois pieds. Couvercle bombé avec bouton en disque.\n16 x 16 cm." },
    it: { hook: "Svizzera, probabilmente Zurigo, XVII/XVIII secolo.", desc: "Svizzera, probabilmente Zurigo, XVII/XVIII secolo. Fusione di campana. Forma rotonda su tre piedi. Coperchio a cupola con pomello a disco.\n16 x 16 cm." }
  },
  5: {
    en: { hook: "Josef Hoffmann built a large house for Moritz Gallia in 1912.", desc: "Attributed to Josef Hoffmann / Wiener Werkstätte.\nIn 1912, Josef Hoffmann built a large house for Moritz Gallia. For the interior, Hoffmann commissioned the Wiener Werkstätte to produce the light fixtures.\nOur lamp is a variant of those used in the Moritz Gallia house. The difference is that the brass ring features a different decor.\nThe hand-cut glass beads are mounted on strong wire, creating a stable glass bowl (basket). This is mounted on a (removable) brass ring. All parts are original and in excellent condition.\n25 x 35 cm.\n(H x D)\nRef: Deutsche Kunst und Dekoration, 1915-1916, Vol. 37, p. 405; Contemporary photograph in the Wiener Werkstätte photo archive, MAK Vienna, Inv. No. KI 9277-4; Wiener Werkstätte Archive: Inventory number: WWF 98-92-4." },
    fr: { hook: "Josef Hoffmann construisit une grande maison pour Moritz Gallia en 1912.", desc: "Attribué à Josef Hoffmann / Wiener Werkstätte.\nEn 1912, Josef Hoffmann construisit une grande maison pour Moritz Gallia. Pour l'aménagement de la maison, Hoffmann chargea la Wiener Werkstätte de fabriquer les luminaires.\nNotre lampe est une variante de celles utilisées dans la maison de Moritz Gallia. La différence réside dans le décor différent de l'anneau en laiton.\nLes perles de verre taillées à la main sont montées sur un fil solide, créant ainsi une coupe en verre stable (panier). Celle-ci est montée sur un anneau (amovible) en laiton. Toutes les pièces sont d'origine et en excellent état.\n25 x 35 cm.\n(H x D)\nRéf: Deutsche Kunst und Dekoration, 1915-1916, Vol. 37, p. 405; Photographie d'époque dans les archives photographiques de la Wiener Werkstätte, MAK Vienne, Inv. n° KI 9277-4; Archives de la Wiener Werkstätte: Numéro d'inventaire WWF 98-92-4." },
    it: { hook: "Josef Hoffmann costruì una grande casa per Moritz Gallia nel 1912.", desc: "Attribuito a Josef Hoffmann / Wiener Werkstätte.\nNel 1912, Josef Hoffmann costruì una grande casa per Moritz Gallia. Per l'arredamento della casa, Hoffmann incaricò la Wiener Werkstätte di realizzare i corpi illuminanti.\nLa nostra lampada è una variante di quelle utilizzate nella casa di Moritz Gallia. La differenza sta nel fatto che l'anello di ottone presenta una decorazione diversa.\nLe perle di vetro molate a mano sono montate su un filo robusto, creando così una coppa di vetro stabile (cesto). Questa è montata su un anello (rimovibile) in ottone. Tutte le parti sono originali e in condizioni eccellenti.\n25 x 35 cm.\n(A x D)\nBibl: Deutsche Kunst und Dekoration, 1915-1916, Vol. 37, p. 405; Fotografia d'epoca nell'archivio fotografico della Wiener Werkstätte, MAK Vienna, Inv. n. KI 9277-4; Archivio della Wiener Werkstätte: Numero di inventario WWF 98-92-4." }
  },
  6: {
    en: { hook: "Pink-tinted clear glass with green layered melt.", desc: "Design by Antonio da Ros (1936-2012). Execution by Gino Cenedese, circa 1960. Pink-tinted clear glass with green layered melt.\nL = 34 cm." },
    fr: { hook: "Verre transparent teinté rose avec fonte en couches vertes.", desc: "Conception d'Antonio da Ros (1936-2012). Exécution par Gino Cenedese, vers 1960. Verre transparent teinté rose avec fonte en couches vertes.\nL = 34 cm." },
    it: { hook: "Vetro trasparente colorato rosa con fusione a strati verdi.", desc: "Disegno di Antonio da Ros (1936-2012). Esecuzione di Gino Cenedese, circa 1960. Vetro trasparente colorato rosa con fusione a strati verdi.\nL = 34 cm." }
  },
  7: {
    en: { hook: "Clear glass with metal oxides and silver foil inclusions.", desc: "Design by Ercole Barovier. Manufacturer: Barovier & Toso.\nClear glass with metal oxides and silver foil inclusions.\nH = 27 cm.\nDesigned 1935-36. The technique was first presented at the 1938 Venice Biennale." },
    fr: { hook: "Verre transparent avec oxydes métalliques et inclusions de feuille d'argent.", desc: "Conception d'Ercole Barovier. Fabricant: Barovier & Toso.\nVerre transparent avec oxydes métalliques et inclusions de feuille d'argent.\nH = 27 cm.\nConçu en 1935-36. La technique fut présentée pour la première fois à la Biennale de Venise en 1938." },
    it: { hook: "Vetro trasparente con ossidi metallici e inclusioni di foglia d'argento.", desc: "Disegno di Ercole Barovier. Produttore: Barovier & Toso.\nVetro trasparente con ossidi metallici e inclusioni di foglia d'argento.\nH = 27 cm.\nProgettato nel 1935-36. La tecnica fu presentata per la prima volta alla Biennale di Venezia del 1938." }
  },
  8: {
    en: { hook: "Pierre d'Avesn vase \"aux Poissons\" designed by Pierre Girre (1901-1990).", desc: "Pierre d'Avesn vase \"aux Poissons\". Design: Pierre Girre (1901-1990). Marked on the base: P. d'Avesn France.\n28 x 26 cm.\nPierre Girre was a former collaborator and designer at René Lalique and studied under François Décorchemont. He used the name P. d'Avesn as an artist's name after leaving Lalique to start his own studio." },
    fr: { hook: "Vase Pierre d'Avesn \"aux Poissons\" conçu par Pierre Girre (1901-1990).", desc: "Vase Pierre d'Avesn \"aux Poissons\". Conception: Pierre Girre (1901-1990). Marqué sur le pied: P. d'Avesn France.\n28 x 26 cm.\nPierre Girre était un ancien collaborateur et designer chez René Lalique et étudia sous François Décorchemont. Il utilisa le nom P. d'Avesn comme nom d'artiste après avoir quitté Lalique pour créer son propre atelier." },
    it: { hook: "Vaso Pierre d'Avesn \"aux Poissons\" disegnato da Pierre Girre (1901-1990).", desc: "Vaso Pierre d'Avesn \"aux Poissons\". Disegno: Pierre Girre (1901-1990). Contrassegnato sulla base: P. d'Avesn France.\n28 x 26 cm.\nPierre Girre fu un ex collaboratore e designer di René Lalique e studiò con François Décorchemont. Utilizzò il nome P. d'Avesn come nome d'arte dopo aver lasciato Lalique per aprire un proprio studio." }
  },
  9: {
    en: { hook: "Attributed to BAG TURGI. Brass, opal glass and frosted clear glass.", desc: "Attributed to BAG TURGI. Brass, opal glass and frosted clear glass.\nD = 25 cm." },
    fr: { hook: "Attribué à BAG TURGI. Laiton, verre opalin et verre transparent dépoli.", desc: "Attribué à BAG TURGI. Laiton, verre opalin et verre transparent dépoli.\nD = 25 cm." },
    it: { hook: "Attribuito a BAG TURGI. Ottone, vetro opale e vetro trasparente satinato.", desc: "Attribuito a BAG TURGI. Ottone, vetro opale e vetro trasparente satinato.\nD = 25 cm." }
  },
  10: {
    en: { hook: "Venezia-Murano Compagny (1872-1909).", desc: "Vittorio Toso Borella (1878-1915) / Francesco Toso Borella (1846-1905) for VMC. Venezia-Murano Compagny (1872-1909). An earlier attribution is Salviati & Co.\nClear glass with enamel painting, after a Renaissance model from around 1500.\nH = 14 cm, D = 10.5 cm." },
    fr: { hook: "Venezia-Murano Compagny (1872-1909).", desc: "Vittorio Toso Borella (1878-1915) / Francesco Toso Borella (1846-1905) pour VMC. Venezia-Murano Compagny (1872-1909). Une attribution antérieure est Salviati & Co.\nVerre transparent avec peinture émaillée, d'après un modèle Renaissance d'environ 1500.\nH = 14 cm, D = 10,5 cm." },
    it: { hook: "Venezia-Murano Compagny (1872-1909).", desc: "Vittorio Toso Borella (1878-1915) / Francesco Toso Borella (1846-1905) per VMC. Venezia-Murano Compagny (1872-1909). Un'attribuzione precedente è Salviati & Co.\nVetro trasparente con pittura a smalto, secondo un modello rinascimentale del 1500 circa.\nA = 14 cm, D = 10,5 cm." }
  },
  11: {
    en: { hook: "\"Opalino a Fiamma\" vase for Barovier & Toso, circa 1957.", desc: "Ercole Barovier.\n\"Opalino a Fiamma\" vase for Barovier & Toso, circa 1957.\nCylindrical form. Clear glass with opaline fused inclusions in the shape of leaves.\n40 cm (15.74 in).\nRef: Marina Barovier. Art of the Barovier glassmakers in Murano 1866-1972. P. 180, No. 154." },
    fr: { hook: "Vase \"Opalino a Fiamma\" pour Barovier & Toso, vers 1957.", desc: "Ercole Barovier.\nVase \"Opalino a Fiamma\" pour Barovier & Toso, vers 1957.\nForme cylindrique. Verre transparent avec inclusions opalines fusionnées en forme de feuilles.\n40 cm (15,74 in).\nRéf: Marina Barovier. Art of the Barovier glassmakers in Murano 1866-1972. P. 180, N° 154." },
    it: { hook: "Vaso \"Opalino a Fiamma\" per Barovier & Toso, circa 1957.", desc: "Ercole Barovier.\nVaso \"Opalino a Fiamma\" per Barovier & Toso, circa 1957.\nForma cilindrica. Vetro trasparente con inclusioni opaline fuse a forma di foglie.\n40 cm (15,74 in).\nBibl: Marina Barovier. Art of the Barovier glassmakers in Murano 1866-1972. P. 180, N. 154." }
  },
  12: {
    en: { hook: "Manfredo Borsi (1900-1967) - Two ceramic portrait panels, circa 1950.", desc: "Manfredo Borsi (1900-1967).\nPortraits, circa 1950. Two counterparts. Painted ceramic plates, glazed and framed.\nEach 64 x 48 cm (25.2 x 18.89 in).\nManfredo Borsi, born in Florence in 1900, began a gilder's apprenticeship in 1916 and sympathised with the Futurism movement founded by Tommaso Marinetti with his 1909 Futurist Manifesto, which developed into a major and significant art movement for Italy.\nIn 1920, M. B. went to Scandinavia. He worked as an interior designer and trained further as a ceramist. Five years later, in 1925, he settled in Paris and had various exhibitions. After the war, in 1948, he moved to Saint-Paul-de-Vence in southern France, where he achieved great success as a ceramic and enamel artist." },
    fr: { hook: "Manfredo Borsi (1900-1967) - Deux plaques de portraits en céramique, vers 1950.", desc: "Manfredo Borsi (1900-1967).\nPortraits, vers 1950. Deux pendants. Plaques en céramique peintes, émaillées et encadrées.\nChacune 64 x 48 cm (25,2 x 18,89 in).\nManfredo Borsi, né à Florence en 1900, commença un apprentissage de doreur en 1916 et sympathisa avec le mouvement futuriste fondé par Tommaso Marinetti avec son Manifeste futuriste de 1909, qui donna naissance à un mouvement artistique majeur et important pour l'Italie.\nEn 1920, M. B. partit en Scandinavie. Il travailla comme décorateur d'intérieur et se perfectionna comme céramiste. Cinq ans plus tard, en 1925, il s'installa à Paris et fit diverses expositions. Après la guerre, en 1948, il partit dans le sud de la France, à Saint-Paul-de-Vence, où il connut un grand succès en tant qu'artiste céramiste et émailleur." },
    it: { hook: "Manfredo Borsi (1900-1967) - Due pannelli di ritratti in ceramica, circa 1950.", desc: "Manfredo Borsi (1900-1967).\nRitratti, circa 1950. Due pendant. Piatti in ceramica dipinti, smaltati e incorniciati.\nCiascuno 64 x 48 cm (25,2 x 18,89 in).\nManfredo Borsi, nato a Firenze nel 1900, iniziò l'apprendistato di doratore nel 1916 e simpatizzò con il movimento futurista fondato da Tommaso Marinetti con il suo Manifesto futurista del 1909, da cui si sviluppò una grande e importante corrente artistica per l'Italia.\nNel 1920, M. B. andò in Scandinavia. Lavorò come arredatore e si formò ulteriormente come ceramista. Cinque anni dopo, nel 1925, si stabilì a Parigi e tenne varie mostre. Dopo la guerra, nel 1948, andò nel sud della Francia, a Saint-Paul-de-Vence, dove ottenne grandi successi come artista ceramista e smaltatore." }
  },
  13: {
    en: { hook: "Carlo Nason / Mazzega, circa 1970.", desc: "Carlo Nason / Mazzega, circa 1970. Two nested glass shades. The outer shade in Vetro Coroso clear glass. The inner shade in opal glass.\nH without cable = 40 cm. D = 25 cm." },
    fr: { hook: "Carlo Nason / Mazzega, vers 1970.", desc: "Carlo Nason / Mazzega, vers 1970. Deux abat-jours en verre emboîtés. L'abat-jour extérieur en verre transparent Vetro Coroso. L'abat-jour intérieur en verre opalin.\nH sans câble = 40 cm. D = 25 cm." },
    it: { hook: "Carlo Nason / Mazzega, circa 1970.", desc: "Carlo Nason / Mazzega, circa 1970. Due paralumi in vetro inseriti l'uno nell'altro. Il paralume esterno in vetro trasparente Vetro Coroso. Il paralume interno in vetro opale.\nA senza cavo = 40 cm. D = 25 cm." }
  },
  14: {
    en: { hook: "Barovier & Toso large Crepuscolo lamp base designed by Ercole Barovier, circa 1935/36.", desc: "Barovier & Toso large Crepuscolo lamp base. Design: Ercole Barovier, circa 1935/36.\nD = 30 cm / H 46 cm (without shade)." },
    fr: { hook: "Grand pied de lampe Crepuscolo Barovier & Toso conçu par Ercole Barovier, vers 1935/36.", desc: "Barovier & Toso grand pied de lampe Crepuscolo. Conception: Ercole Barovier, vers 1935/36.\nD = 30 cm / H 46 cm (sans abat-jour)." },
    it: { hook: "Grande base per lampada Crepuscolo di Barovier & Toso, disegnata da Ercole Barovier, circa 1935/36.", desc: "Barovier & Toso grande base per lampada Crepuscolo. Disegno: Ercole Barovier, circa 1935/36.\nD = 30 cm / A 46 cm (senza paralume)." }
  },
  15: {
    en: { hook: "Glass sculpture / painting, Tesserete, Switzerland, circa 1910.", desc: "Glass sculpture / painting, Tesserete, Switzerland, circa 1910. Murrines assembled into a rectangular image, in a blackened metal stand.\nOverall size: 61 x 38 x 12 cm.\nGlass panel: 46 x 27.5 cm.\nProvenance: Galerie Sanske, Zurich.\nHe lives and works in Tesserete, Switzerland. In 1980 he began his career as a glass artist making elaborate stained glass windows. In the early 1990s he deepened his knowledge of glass art by participating in fusing seminars with various artists, including Giles Bettison, Matthew Curtis, Linda Ethier and Rudi Gritsch." },
    fr: { hook: "Sculpture / tableau en verre, Tesserete, Suisse, vers 1910.", desc: "Sculpture / tableau en verre, Tesserete, Suisse, vers 1910. Murrines assemblées en une image rectangulaire, dans un support métallique noirci.\nDimensions totales: 61 x 38 x 12 cm.\nPlaque de verre: 46 x 27,5 cm.\nProvenance: Galerie Sanske, Zurich.\nIl vit et travaille à Tesserete, Suisse. En 1980, il commença sa carrière d'artiste verrier en réalisant d'élaborés vitraux. Au début des années 1990, il approfondit ses connaissances en art du verre en participant à des séminaires de fusing avec divers artistes, notamment Giles Bettison, Matthew Curtis, Linda Ethier et Rudi Gritsch." },
    it: { hook: "Scultura / quadro in vetro, Tesserete, Svizzera, circa 1910.", desc: "Scultura / quadro in vetro, Tesserete, Svizzera, circa 1910. Murrine assemblate in un'immagine rettangolare, in supporto metallico annerito.\nDimensioni totali: 61 x 38 x 12 cm.\nLastra di vetro: 46 x 27,5 cm.\nProvenienza: Galerie Sanske, Zurigo.\nVive e lavora a Tesserete, Svizzera. Nel 1980 iniziò la carriera di artista del vetro realizzando elaborate vetrate. All'inizio degli anni '90 approfondì la conoscenza dell'arte del vetro partecipando a seminari di fusing con vari artisti, tra cui Giles Bettison, Matthew Curtis, Linda Ethier e Rudi Gritsch." }
  },
  16: {
    en: { hook: "Sculptural \"Murrini\" vase from the Kenya series, 2009.", desc: "Sculptural \"Murrini\" vase from the Kenya series, 2009. Mouth-blown, cut, red-beige Murrine vase. Signed on the base with Murrine signature.\nH = 47.5 cm.\nProvenance: Galerie Sanske, Zurich.\nHe lives and works in Tesserete, Switzerland. In 1980 he began his career as a glass artist making elaborate stained glass windows. In the early 1990s he deepened his knowledge of glass art by participating in fusing seminars with various artists, including Giles Bettison, Matthew Curtis, Linda Ethier and Rudi Gritsch." },
    fr: { hook: "Vase sculptural \"Murrini\" de la série Kenya, 2009.", desc: "Vase sculptural \"Murrini\" de la série Kenya, 2009. Vase Murrine rouge-beige soufflé à la bouche et taillé. Signé au fond avec la signature Murrine.\nH = 47,5 cm.\nProvenance: Galerie Sanske, Zurich.\nIl vit et travaille à Tesserete, Suisse. En 1980, il commença sa carrière d'artiste verrier en réalisant d'élaborés vitraux. Au début des années 1990, il approfondit ses connaissances en art du verre en participant à des séminaires de fusing avec divers artistes, notamment Giles Bettison, Matthew Curtis, Linda Ethier et Rudi Gritsch." },
    it: { hook: "Vaso scultoreo \"Murrini\" della serie Kenya, 2009.", desc: "Vaso scultoreo \"Murrini\" della serie Kenya, 2009. Vaso Murrine rosso-beige soffiato a bocca e molato. Firmato sul fondo con firma Murrine.\nA = 47,5 cm.\nProvenienza: Galerie Sanske, Zurigo.\nVive e lavora a Tesserete, Svizzera. Nel 1980 iniziò la carriera di artista del vetro realizzando elaborate vetrate. All'inizio degli anni '90 approfondì la conoscenza dell'arte del vetro partecipando a seminari di fusing con vari artisti, tra cui Giles Bettison, Matthew Curtis, Linda Ethier e Rudi Gritsch." }
  },
  17: {
    en: { hook: "Oriente vase, model 3119, Vetreria Aureliano, Murano, 1950s.", desc: "Oriente vase, model 3119, Vetreria Aureliano, Murano, 1950s. Design by Dino Martens. H = 28.5 cm.\nGlass body with fused glass powder, coloured glass pieces, Zanfirico rods and the typical star-shaped glass piece. These are heated, further blown out and cased with clear glass.\nRef: Marc Heiremans. Arnoldsche. Dino Martens Muranese Glass Designer. P. 169, A 120." },
    fr: { hook: "Vase Oriente, modèle 3119, Vetreria Aureliano, Murano, années 1950.", desc: "Vase Oriente, modèle 3119, Vetreria Aureliano, Murano, années 1950. Conception de Dino Martens. H = 28,5 cm.\nCorps en verre avec poudre de verre fondue, morceaux de verre colorés, tiges Zanfirico et la caractéristique pièce de verre en forme d'étoile. Ceux-ci sont chauffés, soufflés davantage et recouverts de verre transparent.\nRéf: Marc Heiremans. Arnoldsche. Dino Martens Muranese Glass Designer. P. 169, A 120." },
    it: { hook: "Vaso Oriente, modello 3119, Vetreria Aureliano, Murano, anni '50.", desc: "Vaso Oriente, modello 3119, Vetreria Aureliano, Murano, anni '50. Disegno di Dino Martens. A = 28,5 cm.\nCorpo in vetro con polvere di vetro fusa, pezzi di vetro colorati, canne Zanfirico e il caratteristico pezzo di vetro a forma di stella. Questi vengono riscaldati, ulteriormente soffiati e sovrapposti con vetro trasparente.\nBibl: Marc Heiremans. Arnoldsche. Dino Martens Muranese Glass Designer. P. 169, A 120." }
  },
  18: {
    en: { hook: "Parnasso vase from the Eldorado series, model no. 4244, Vetreria Aureliano Toso, Murano circa 1953.", desc: "Parnasso vase from the Eldorado series, model no. 4244, Vetreria Aureliano Toso, Murano circa 1953. Design by Dino Martens (1894-1970). With original Aureliano Toso manufacturer's label. H = 35 cm.\nEldorado technique: This name refers to the scattered Aventurina particles. The manufacturing process corresponds to that of the Oriente technique. The difference lies in the use of transparent, pulverised glass and the scattered Aventurina. This technique was introduced in 1952. No further models are known after 1954.\nRef: Marc Heiremans. Arnoldsche. Dino Martens, Muranese Glass Designer. P. 83, fig. 62 and P. 165, A 87." },
    fr: { hook: "Vase Parnasso de la série Eldorado, modèle n° 4244, Vetreria Aureliano Toso, Murano vers 1953.", desc: "Vase Parnasso de la série Eldorado, modèle n° 4244, Vetreria Aureliano Toso, Murano vers 1953. Conception de Dino Martens (1894-1970). Avec étiquette d'origine du fabricant Aureliano Toso. H = 35 cm.\nTechnique Eldorado: Ce nom se réfère aux particules d'Aventurina dispersées. Le processus de fabrication correspond à celui de la technique Oriente. La différence réside dans l'utilisation de verre transparent pulvérisé et de l'Aventurina dispersée. Cette technique fut introduite en 1952. Aucun autre modèle n'est connu après 1954.\nRéf: Marc Heiremans. Arnoldsche. Dino Martens, Muranese Glass Designer. P. 83, fig. 62 et P. 165, A 87." },
    it: { hook: "Vaso Parnasso della serie Eldorado, modello n. 4244, Vetreria Aureliano Toso, Murano circa 1953.", desc: "Vaso Parnasso della serie Eldorado, modello n. 4244, Vetreria Aureliano Toso, Murano circa 1953. Disegno di Dino Martens (1894-1970). Con etichetta originale del produttore Aureliano Toso. A = 35 cm.\nTecnica Eldorado: Questo nome si riferisce alle particelle di Aventurina disperse. Il processo di produzione corrisponde a quello della tecnica Oriente. La differenza sta nell'uso di vetro trasparente polverizzato e dell'Aventurina dispersa. Questa tecnica fu introdotta nel 1952. Non si conoscono altri modelli dopo il 1954.\nBibl: Marc Heiremans. Arnoldsche. Dino Martens, Muranese Glass Designer. P. 83, fig. 62 e P. 165, A 87." }
  },
  19: {
    en: { hook: "Beautiful and rare plate by French artist Edmond Lachenal, France, late 19th century.", desc: "Beautiful and rare plate by French artist Edmond Lachenal, France, late 19th century. Ceramic painted with grape decoration. Minor chips on the rim. D = 33 cm.\nEdmond Lachenal was a famous ceramic artist of the late 19th century and was particularly appreciated by the great artists of his time, such as Rodin, for whom he crafted the head of La Douleur and the head of Balzac. His early artistic years were shaped by the influence of Théodore Deck, under whom he trained. In the 1880s, Lachenal produced numerous pieces that recalled Iznik or Kubatcha ceramics in form and decor." },
    fr: { hook: "Beau et rare plat de l'artiste français Edmond Lachenal, France, fin XIXe siècle.", desc: "Beau et rare plat de l'artiste français Edmond Lachenal, France, fin XIXe siècle. Céramique peinte avec décor de raisins. Petites ébréchures sur le bord. D = 33 cm.\nEdmond Lachenal était un célèbre céramiste de la fin du XIXe siècle particulièrement apprécié par les grands artistes de son temps, tels que Rodin, pour qui il réalisa la tête de La Douleur ainsi que la tête de Balzac. Ses premières années artistiques furent marquées par l'influence de Théodore Deck, chez qui il fit son apprentissage. Dans les années 1880, Lachenal réalisa de nombreuses pièces dont la forme et le décor rappellent les céramiques d'Iznik ou de Kubatcha." },
    it: { hook: "Bel piatto raro dell'artista francese Edmond Lachenal, Francia, fine XIX secolo.", desc: "Bel piatto raro dell'artista francese Edmond Lachenal, Francia, fine XIX secolo. Ceramica dipinta con decoro d'uva. Piccole scheggiature sul bordo. D = 33 cm.\nEdmond Lachenal fu un famoso ceramista della fine del XIX secolo particolarmente apprezzato dai grandi artisti del suo tempo, come Rodin, per il quale realizzò la testa de La Douleur e la testa di Balzac. I suoi primi anni artistici furono segnati dall'influenza di Théodore Deck, presso il quale fece l'apprendistato. Negli anni '80 dell'800, Lachenal realizzò numerosi pezzi che ricordavano nella forma e nel decoro le ceramiche di Iznik o di Kubatcha." }
  },
  20: {
    en: { hook: "Signed Asteroid, probably France, circa 1950.", desc: "Signed Asteroid, probably France, circa 1950. Pressed glass with brass mounts.\n65 x 33 cm." },
    fr: { hook: "Signé Asteroid, probablement France, vers 1950.", desc: "Signé Asteroid, probablement France, vers 1950. Verre pressé avec montures en laiton.\n65 x 33 cm." },
    it: { hook: "Firmato Asteroid, probabilmente Francia, circa 1950.", desc: "Firmato Asteroid, probabilmente Francia, circa 1950. Vetro pressato con montature in ottone.\n65 x 33 cm." }
  },
  21: {
    en: { hook: "Venini large and rare lamp base in Opalino glass designed by Paolo Venini, circa 1952.", desc: "Venini large and rare lamp base in Opalino glass. Design: Paolo Venini, circa 1952. Round etched signature from the 1950s: Venini murano Italia. H = 56 cm." },
    fr: { hook: "Grand et rare pied de lampe Venini en verre Opalino, conçu par Paolo Venini, vers 1952.", desc: "Venini grand et rare pied de lampe en verre Opalino. Conception: Paolo Venini, vers 1952. Signature ronde gravée des années 1950: Venini murano Italia. H = 56 cm." },
    it: { hook: "Grande e rara base per lampada Venini in vetro Opalino, disegnata da Paolo Venini, circa 1952.", desc: "Venini grande e rara base per lampada in vetro Opalino. Disegno: Paolo Venini, circa 1952. Firma rotonda incisa degli anni '50: Venini murano Italia. A = 56 cm." }
  },
  22: {
    en: { hook: "Clear glass with fused amber-coloured Pezzati.", desc: "Design by Ercole Barovier.\n\"Pezzato\" bowl, designed by Ercole Barovier for Barovier & Toso, 1956. Cylindrical body. Clear glass with fused amber-coloured Pezzati.\n10.5 x 13.5 cm." },
    fr: { hook: "Verre transparent avec Pezzati ambrés fusionnés.", desc: "Conception d'Ercole Barovier.\nCoupe \"Pezzato\", conçue par Ercole Barovier pour Barovier & Toso, 1956. Corps cylindrique. Verre transparent avec Pezzati ambrés fusionnés.\n10,5 x 13,5 cm." },
    it: { hook: "Vetro trasparente con Pezzati color ambra fusi.", desc: "Disegno di Ercole Barovier.\nCoppa \"Pezzato\", disegnata da Ercole Barovier per Barovier & Toso, 1956. Corpo cilindrico. Vetro trasparente con Pezzati color ambra fusi.\n10,5 x 13,5 cm." }
  },
  23: {
    en: { hook: "Murrine Floreali vase, Vetreria Fratelli Toso, Murano circa 1920.", desc: "Murrine Floreali vase, Vetreria Fratelli Toso, Murano circa 1920. White glass, blue overlay with fused Murrine flowers.\nH = 15 cm." },
    fr: { hook: "Vase Murrine Floreali, Vetreria Fratelli Toso, Murano vers 1920.", desc: "Vase Murrine Floreali, Vetreria Fratelli Toso, Murano vers 1920. Verre blanc, doublage bleu avec fleurs Murrine fusionnées.\nH = 15 cm." },
    it: { hook: "Vaso Murrine Floreali, Vetreria Fratelli Toso, Murano circa 1920.", desc: "Vaso Murrine Floreali, Vetreria Fratelli Toso, Murano circa 1920. Vetro bianco, sovrapposizione blu con fiori Murrine fusi.\nA = 15 cm." }
  },
  24: {
    en: { hook: "Spherical vase with star-shaped murrines in white, yellow and orange-red glass.", desc: "Spherical vase with star-shaped murrines in white, yellow and orange-red glass. Made by Fratelli Toso, Murano circa 1950. Design by Ermanno Toso.\nH = 23 cm." },
    fr: { hook: "Vase sphérique avec murrines en forme d'étoile en verre blanc, jaune et rouge-orange.", desc: "Vase sphérique avec murrines en forme d'étoile en verre blanc, jaune et rouge-orange. Fabriqué par Fratelli Toso, Murano vers 1950. Conception d'Ermanno Toso.\nH = 23 cm." },
    it: { hook: "Vaso sferico con murrine a forma di stella in vetro bianco, giallo e rosso-arancio.", desc: "Vaso sferico con murrine a forma di stella in vetro bianco, giallo e rosso-arancio. Prodotto da Fratelli Toso, Murano circa 1950. Disegno di Ermanno Toso.\nA = 23 cm." }
  },
  25: {
    en: { hook: "Cast iron painted silver.", desc: "Garden chair designed by Karl Friedrich Schinkel (1781-1841). Cast iron painted silver. One rear leg strut is missing.\n77 x 48 x 51 cm.\nAround 1825, Karl Friedrich Schinkel designed iron furniture for the Prussian royal family, including an iron garden chair for the \"Roman Baths\" in Sanssouci Park in Potsdam. Many later models vary this prototype in the design of the backrest ornament and the omission of smaller motifs such as goat's feet, ram's heads on the armrests, or small palmettes.\nOur chair, which is probably also based on a Schinkel design, is such a reduced variant. An identical chair with the same backrest can be found in the Grassi Museum for Applied Art as well as the Museum of Applied Art (MAK) in Frankfurt/Main. The one in Frankfurt was cast in the Sayn foundry in the mid-19th century. Manufacture: Prussian/Bohemian foundry. We assume our chair also comes from this production." },
    fr: { hook: "Fonte peinte en argenté.", desc: "Fauteuil de jardin conçu par Karl Friedrich Schinkel (1781-1841). Fonte peinte en argenté. Une traverse arrière au niveau des pieds est manquante.\n77 x 48 x 51 cm.\nVers 1825, Karl Friedrich Schinkel avait conçu du mobilier en fer pour la famille royale prussienne, notamment une chaise de jardin en fer pour les \"Bains romains\" dans le parc de Sanssouci à Potsdam. De nombreux modèles ultérieurs varient ce prototype dans la conception de l'ornement du dossier et l'omission de motifs plus petits tels que les pieds de bouc, les têtes de bélier sur les accoudoirs ou les petites palmettes.\nNotre chaise, qui remonte probablement aussi à un dessin de Schinkel, est une telle variante réduite. Une chaise identique avec le même dossier se trouve au Grassi Museum für Angewandte Kunst ainsi qu'au Museum für angewandte Kunst (MAK) de Francfort/Main. Celle de Francfort fut coulée à la fonderie de Sayn au milieu du XIXe siècle. Fabrication: fonderie prussienne/bohémienne. Nous supposons que notre chaise provient également de cette production." },
    it: { hook: "Ghisa dipinta in argento.", desc: "Poltrona da giardino disegnata da Karl Friedrich Schinkel (1781-1841). Ghisa dipinta in argento. Manca una traversa posteriore all'altezza dei piedi.\n77 x 48 x 51 cm.\nIntorno al 1825, Karl Friedrich Schinkel disegnò mobili in ferro per la famiglia reale prussiana, tra cui una sedia da giardino in ferro per i \"Bagni Romani\" nel parco di Sanssouci a Potsdam. Molti modelli successivi variano questo prototipo nel disegno dell'ornamento della spalliera e nell'omissione di motivi più piccoli come piedi di capra, teste di ariete sui braccioli o piccole palmette.\nLa nostra sedia, probabilmente anch'essa basata su un disegno di Schinkel, è una tale variante ridotta. Una sedia identica con la stessa spalliera si trova al Grassi Museum für Angewandte Kunst così come al Museum für angewandte Kunst (MAK) di Francoforte sul Meno. Quella di Francoforte fu fusa nella fonderia di Sayn a metà del XIX secolo. Produzione: fonderia prussiana/boema. Supponiamo che anche la nostra sedia provenga da questa produzione." }
  },
  26: {
    en: { hook: "Variation from the \"Lenti\" series.", desc: "1938. Design: Ercole Barovier. Manufacturer: Barovier & Toso.\nVariation from the \"Lenti\" series.\n27 x 23 x 16 cm." },
    fr: { hook: "Variation de la série \"Lenti\".", desc: "1938. Conception: Ercole Barovier. Fabricant: Barovier & Toso.\nVariation de la série \"Lenti\".\n27 x 23 x 16 cm." },
    it: { hook: "Variazione della serie \"Lenti\".", desc: "1938. Disegno: Ercole Barovier. Produttore: Barovier & Toso.\nVariazione della serie \"Lenti\".\n27 x 23 x 16 cm." }
  },
  27: {
    en: { hook: "Fire-polished vase \"Aux Fougères\" by Emile Gallé (1846-1904), circa 1900.", desc: "Fire-polished vase, \"Aux Fougères\" by Emile Gallé (1846-1904), circa 1900. Cameo glass, etched, cut and polished in several stages. Japonesque signature on the wall.\nH = 41 cm.\nFrench Art Nouveau fire-polished cameo glass vase with fern pattern by Emile Gallé (1846-1904)." },
    fr: { hook: "Vase feuilleté \"Aux Fougères\" d'Emile Gallé (1846-1904), vers 1900.", desc: "Vase feuilleté, \"Aux Fougères\" d'Emile Gallé (1846-1904), vers 1900. Verre camée gravé, taillé et poli en plusieurs étapes. Signature japonisante sur la paroi.\nH = 41 cm.\nVase Art Nouveau français en verre camée feuilleté avec motif de fougère par Emile Gallé (1846-1904)." },
    it: { hook: "Vaso a fuoco polito \"Aux Fougères\" di Emile Gallé (1846-1904), circa 1900.", desc: "Vaso a fuoco polito, \"Aux Fougères\" di Emile Gallé (1846-1904), circa 1900. Vetro cameo inciso, molato e lucidato in più fasi. Firma giapponesizzante sulla parete.\nA = 41 cm.\nVaso Art Nouveau francese in vetro cameo a fuoco polito con motivo di felce di Emile Gallé (1846-1904)." }
  },
  28: {
    en: { hook: "Rare cubist Bauhaus vase by W. Goebel Oeslau.", desc: "Rare cubist Bauhaus vase by W. Goebel Oeslau, Germany, circa 1920/35. Ceramic with green glaze and splash decoration. Cylindrical form with two cubist handles. Company signet on the base.\nH = 23 cm." },
    fr: { hook: "Rare vase cubiste Bauhaus de W. Goebel Oeslau.", desc: "Rare vase cubiste Bauhaus de W. Goebel Oeslau, Allemagne, vers 1920/35. Céramique émaillée verte avec décor de projection. Forme cylindrique avec deux anses cubistes. Signet de la maison sur le pied.\nH = 23 cm." },
    it: { hook: "Raro vaso cubista Bauhaus della W. Goebel Oeslau.", desc: "Raro vaso cubista Bauhaus della W. Goebel Oeslau, Germania, circa 1920/35. Ceramica smaltata verde con decoro a spruzzo. Forma cilindrica con due manici cubisti. Marchio della ditta sulla base.\nA = 23 cm." }
  },
  29: {
    en: { hook: "Dancer by Josef Lorenzl for Goldscheider, Vienna, circa 1937.", desc: "Dancer by Josef Lorenzl for Goldscheider, Vienna, circa 1937. Model no. 7582.\n32.5 x 32 x 25 cm.\nAustria circa 1937. Figurine by Josef Lorenzl for Goldscheider." },
    fr: { hook: "Danseuse de Josef Lorenzl pour Goldscheider, Vienne, vers 1937.", desc: "Danseuse de Josef Lorenzl pour Goldscheider, Vienne, vers 1937. Modèle n° 7582.\n32,5 x 32 x 25 cm.\nAutriche vers 1937. Figurine de Josef Lorenzl pour Goldscheider." },
    it: { hook: "Danzatrice di Josef Lorenzl per Goldscheider, Vienna, circa 1937.", desc: "Danzatrice di Josef Lorenzl per Goldscheider, Vienna, circa 1937. Modello n. 7582.\n32,5 x 32 x 25 cm.\nAustria circa 1937. Figurina di Josef Lorenzl per Goldscheider." }
  },
  30: {
    en: { hook: "Plant stand by André Groult, France, 1930s.", desc: "Plant stand by André Groult, France, 1930s. Beechwood.\n96 x 84 x 25 cm.\nPlant stand designed by André Groult, France, 1930s." },
    fr: { hook: "Support de plante par André Groult, France, années 1930.", desc: "Support de plante par André Groult, France, années 1930. Bois de hêtre.\n96 x 84 x 25 cm.\nSupport de plante conçu par André Groult, France, années 1930." },
    it: { hook: "Portapiante di André Groult, Francia, anni '30.", desc: "Portapiante di André Groult, Francia, anni '30. Legno di faggio.\n96 x 84 x 25 cm.\nPortapiante disegnato da André Groult, Francia, anni '30." }
  },
  31: {
    en: { hook: "Manufactured by Wohnbedarf AG from 1948 to circa 1960.", desc: "Armchair model \"1363\". Design by Hans Gugelot, 1948. Manufactured by Wohnbedarf AG from 1948 to circa 1960. Ash wood with fabric upholstery. The chair is adjustable by sliding the seat shell over the backrest.\n90 x 65 x 92 cm." },
    fr: { hook: "Fabriqué par Wohnbedarf AG de 1948 à environ 1960.", desc: "Fauteuil modèle \"1363\". Conception de Hans Gugelot, 1948. Fabriqué par Wohnbedarf AG de 1948 à environ 1960. Frêne avec revêtement en tissu. Le fauteuil est réglable en faisant glisser la coque du siège sur le dossier.\n90 x 65 x 92 cm." },
    it: { hook: "Prodotto da Wohnbedarf AG dal 1948 al 1960 circa.", desc: "Poltrona modello \"1363\". Disegno di Hans Gugelot, 1948. Prodotta da Wohnbedarf AG dal 1948 al 1960 circa. Frassino con rivestimento in tessuto. La poltrona è regolabile facendo scorrere il guscio del sedile sullo schienale.\n90 x 65 x 92 cm." }
  },
  32: {
    en: { hook: "Art Déco chandelier with lobster motif.", desc: "Art Déco chandelier with lobster motif. Probably after a design by Charles Schneider, circa 1920. Bronze with signed glass bowl. Signed: Schneider.\n65 x 55 cm." },
    fr: { hook: "Lustre Art Déco avec motif de homard.", desc: "Lustre Art Déco avec motif de homard. Probablement d'après un dessin de Charles Schneider, vers 1920. Bronze avec coupe en verre signée. Signé: Schneider.\n65 x 55 cm." },
    it: { hook: "Lampadario Art Déco con motivo di aragosta.", desc: "Lampadario Art Déco con motivo di aragosta. Probabilmente da un disegno di Charles Schneider, circa 1920. Bronzo con coppa in vetro firmata. Firmato: Schneider.\n65 x 55 cm." }
  },
  33: {
    en: { hook: "\"Ronco\" armchair with high backrest.", desc: "\"Ronco\" armchair with high backrest. Design by Jacob Müller circa 1950. Manufacturer Wohnhilfe Zürich, circa 1950. Three-position adjustable chair in cherry wood with fabric upholstery.\nWidth 62 cm." },
    fr: { hook: "Fauteuil \"Ronco\" à haut dossier.", desc: "Fauteuil \"Ronco\" à haut dossier. Conception de Jacob Müller vers 1950. Fabricant Wohnhilfe Zurich, vers 1950. Fauteuil réglable en trois positions en cerisier avec revêtement en tissu.\nLargeur 62 cm." },
    it: { hook: "Poltrona \"Ronco\" con schienale alto.", desc: "Poltrona \"Ronco\" con schienale alto. Disegno di Jacob Müller circa 1950. Produttore Wohnhilfe Zurigo, circa 1950. Poltrona regolabile in tre posizioni in ciliegio con rivestimento in tessuto.\nLarghezza 62 cm." }
  },
  34: {
    en: { hook: "\"Ronco\" armchair with low backrest.", desc: "\"Ronco\" armchair with low backrest. Design by Jacob Müller. Manufacturer Wohnhilfe Zürich circa 1950. Three-position adjustable chair in ash wood with fabric upholstery.\nWidth: 62 cm." },
    fr: { hook: "Fauteuil \"Ronco\" à dossier bas.", desc: "Fauteuil \"Ronco\" à dossier bas. Conception de Jacob Müller. Fabricant Wohnhilfe Zurich vers 1950. Fauteuil réglable en trois positions en frêne avec revêtement en tissu.\nLargeur: 62 cm." },
    it: { hook: "Poltrona \"Ronco\" con schienale basso.", desc: "Poltrona \"Ronco\" con schienale basso. Disegno di Jacob Müller. Produttore Wohnhilfe Zurigo circa 1950. Poltrona regolabile in tre posizioni in frassino con rivestimento in tessuto.\nLarghezza: 62 cm." }
  },
  35: {
    en: { hook: "Early desk lamp by Jean Perzel, Paris.", desc: "Early desk lamp by Jean Perzel, Paris. Design: 1929 for the library of the \"Cité Universitaire\" in Paris. Brass and white cased glass (glass replaced by Perzel, Paris).\nThe model offered here, with beautiful patina, is an early production from the 1930s and is therefore not signed.\n37 x 20 cm." },
    fr: { hook: "Première lampe de bureau de Jean Perzel, Paris.", desc: "Première lampe de bureau de Jean Perzel, Paris. Conception: 1929 pour la bibliothèque de la \"Cité Universitaire\" à Paris. Laiton et verre doublé blanc (verre remplacé par la maison Perzel, Paris).\nLe modèle proposé ici, avec une belle patine, est une exécution précoce des années 30 et n'est donc pas signé.\n37 x 20 cm." },
    it: { hook: "Prima lampada da scrivania di Jean Perzel, Parigi.", desc: "Prima lampada da scrivania di Jean Perzel, Parigi. Disegno: 1929 per la biblioteca della \"Cité Universitaire\" di Parigi. Ottone e vetro sovrapposto bianco (vetro sostituito dalla ditta Perzel, Parigi).\nIl modello qui offerto, con una bella patina, è una prima esecuzione degli anni '30 e pertanto non è firmato.\n37 x 20 cm." }
  },
  36: {
    en: { hook: "Gilt bronze with glass drops.", desc: "After a design by Josef Hoffmann. Gilt bronze with glass drops. Circa 1900.\n50 x 60 cm.\nRare French version." },
    fr: { hook: "Bronze doré avec pendeloques en verre.", desc: "D'après un dessin de Josef Hoffmann. Bronze doré avec pendeloques en verre. Vers 1900.\n50 x 60 cm.\nRare version française." },
    it: { hook: "Bronzo dorato con pendagli in vetro.", desc: "Da un disegno di Josef Hoffmann. Bronzo dorato con pendagli in vetro. Circa 1900.\n50 x 60 cm.\nRara versione francese." }
  },
  37: {
    en: { hook: "Bronze with green patina on marble base.", desc: "Germaine Oury, circa 1920.\nBronze with green patina on marble base. Signed in the bronze: Germaine Oury, with cire perdue (lost wax) inscription and Susse Frères, Paris foundry stamp.\nH = 38 cm.\nG. O. was born in 1889 in Valenciennes and died in Ville d'Avray in 1978. Her works can be found in: the Musée des Années Trente in Boulogne-Billancourt / Paris, the Musée des Beaux-Arts of Valenciennes, and the Musée d'art et d'histoire du judaïsme in Paris.\nShe exhibited at the Salon d'Hiver in 1935 and 1937." },
    fr: { hook: "Bronze patiné vert sur socle en marbre.", desc: "Germaine Oury, vers 1920.\nBronze patiné vert sur socle en marbre. Signé dans le bronze: Germaine Oury, avec inscription cire perdue et cachet du fondeur Susse Frères, Paris.\nH = 38 cm.\nG. O. est née en 1889 à Valenciennes et décédée à Ville d'Avray en 1978. Ses œuvres se trouvent: au Musée des Années Trente à Boulogne-Billancourt / Paris, au Musée des Beaux-Arts de Valenciennes, et au Musée d'art et d'histoire du judaïsme à Paris.\nElle exposa au Salon d'Hiver en 1935 et 1937." },
    it: { hook: "Bronzo patinato verde su base in marmo.", desc: "Germaine Oury, circa 1920.\nBronzo patinato verde su base in marmo. Firmato nel bronzo: Germaine Oury, con iscrizione cire perdue (a cera persa) e timbro della fonderia Susse Frères, Parigi.\nA = 38 cm.\nG. O. nacque nel 1889 a Valenciennes e morì a Ville d'Avray nel 1978. Le sue opere si trovano: al Musée des Années Trente di Boulogne-Billancourt / Parigi, al Musée des Beaux-Arts di Valenciennes, e al Musée d'art et d'histoire du judaïsme di Parigi.\nEspose al Salon d'Hiver nel 1935 e 1937." }
  },
  38: {
    en: { hook: "Red vase in Sommerso technique with gold shimmer. Manufacturer: Venini. Design: Carlo Scarpa, 1934-36.", desc: "Red vase in Sommerso technique with gold shimmer. Manufacturer: Venini. Design: Carlo Scarpa. Period: 1934-36 circa. Model number: 3597. Unsigned.\nH = 8.5 cm.\nRef: Marino Barovier, CARLO SCARPA VENINI 1932-1947. Skira, P. 141." },
    fr: { hook: "Vase rouge en technique Sommerso avec paillettes d'or. Fabricant: Venini. Conception: Carlo Scarpa, 1934-36.", desc: "Vase rouge en technique Sommerso avec paillettes d'or. Fabricant: Venini. Conception: Carlo Scarpa. Période: 1934-36 environ. Numéro de modèle: 3597. Non signé.\nH = 8,5 cm.\nRéf: Marino Barovier, CARLO SCARPA VENINI 1932-1947. Skira, P. 141." },
    it: { hook: "Vaso rosso in tecnica Sommerso con brillii oro. Produttore: Venini. Disegno: Carlo Scarpa, 1934-36.", desc: "Vaso rosso in tecnica Sommerso con brillii oro. Produttore: Venini. Disegno: Carlo Scarpa. Periodo: 1934-36 circa. Numero modello: 3597. Non firmato.\nA = 8,5 cm.\nBibl: Marino Barovier, CARLO SCARPA VENINI 1932-1947. Skira, P. 141." }
  },
  39: {
    en: { hook: "Large globe lamp, France, 1925-1935.", desc: "Large globe lamp, France, 1925-1935. Design by Philippe Genet and Lucien Michon. Chromed metal, pressed glass frosted and partly polished. Newly electrified. Diameter of the sphere 36 cm.\nL = 110 cm. (The rod can be shortened on request.)" },
    fr: { hook: "Grande lampe globe, France, 1925-1935.", desc: "Grande lampe globe, France, 1925-1935. Conception de Philippe Genet et Lucien Michon. Métal chromé, verre pressé dépoli et partiellement poli. Nouvellement électrifiée. Diamètre de la sphère 36 cm.\nL = 110 cm. (La tige peut être raccourcie sur demande.)" },
    it: { hook: "Grande lampada globo, Francia, 1925-1935.", desc: "Grande lampada globo, Francia, 1925-1935. Disegno di Philippe Genet e Lucien Michon. Metallo cromato, vetro pressato satinato e parzialmente lucidato. Nuovamente elettrificata. Diametro della sfera 36 cm.\nL = 110 cm. (L'asta può essere accorciata su richiesta.)" }
  },
  40: {
    en: { hook: "Brass suspension mount.", desc: "Italy, circa 1950. Height-adjustable. Brass suspension mount. Black lacquered metal shade with white Plexiglass cover.\nA lamp with the same adjustable suspension can be found in the catalogue raisonné of Gino Sarfatti: Marco Romanelli / Sandro Severi. SILVANA Editoriale. Gino Sarfatti opere scelte 1938-1973. Selected Works. P. 120 and 465, as model no. 2039. However with fabric shade." },
    fr: { hook: "Suspension en laiton.", desc: "Italie, vers 1950. Réglable en hauteur. Suspension en laiton. Abat-jour en métal laqué noir avec couvercle en Plexiglas blanc.\nJ'ai trouvé une lampe avec la même suspension réglable dans le catalogue raisonné de Gino Sarfatti: Marco Romanelli / Sandro Severi. SILVANA Editoriale. Gino Sarfatti opere scelte 1938-1973. Selected Works. P. 120 et 465, en tant que modèle n° 2039. Cependant avec abat-jour en tissu." },
    it: { hook: "Sospensione in ottone.", desc: "Italia, circa 1950. Regolabile in altezza. Sospensione in ottone. Paralume in metallo laccato nero con copertura in Plexiglas bianco.\nHo trovato una lampada con la stessa sospensione regolabile nel catalogo ragionato di Gino Sarfatti: Marco Romanelli / Sandro Severi. SILVANA Editoriale. Gino Sarfatti opere scelte 1938-1973. Selected Works. P. 120 e 465, come modello n. 2039. Tuttavia con paralume in tessuto." }
  },
  41: {
    en: { hook: "Amber-coloured bowl with craquelure.", desc: "Amber-coloured bowl with craquelure. Design by Andries Dirk Copier for Glasfabriek Leerdam, Holland, 1928. With triangular etched Serica signature. Small flaw in the glass, see photos.\n12.5 x 25 cm.\nAmber bowl with crackled pattern. Designed by Andries Dirk Copier for Glasfabriek Leerdam, Dutch, 1928. Etched Serica mark on the stand. Small fault inside the glass, see photos." },
    fr: { hook: "Coupe couleur ambre avec craquelure.", desc: "Coupe couleur ambre avec craquelure. Conception d'Andries Dirk Copier pour Glasfabriek Leerdam, Hollande, 1928. Avec signature Serica triangulaire gravée. Petit défaut dans le verre, voir photos.\n12,5 x 25 cm.\nCoupe ambre avec motif craquelé. Conçue par Andries Dirk Copier pour Glasfabriek Leerdam, Pays-Bas, 1928. Marque Serica gravée sur le pied. Petit défaut à l'intérieur du verre, voir photos." },
    it: { hook: "Coppa color ambra con craquelure.", desc: "Coppa color ambra con craquelure. Disegno di Andries Dirk Copier per Glasfabriek Leerdam, Olanda, 1928. Con firma triangolare Serica incisa. Piccolo difetto nel vetro, vedi foto.\n12,5 x 25 cm.\nCoppa ambra con motivo craquelato. Disegnata da Andries Dirk Copier per Glasfabriek Leerdam, Olanda, 1928. Marchio Serica inciso sulla base. Piccolo difetto all'interno del vetro, vedi foto." }
  },
  42: {
    en: { hook: "Bauhaus desk lamp, BAG-Turgi, Switzerland.", desc: "Bauhaus desk lamp, BAG-Turgi, Switzerland.\nModel 4.356, designed 1936. Cast iron base, sheet steel reflector with original brown shrink lacquer. Original electrification, can be renewed on request.\nH = 30 cm." },
    fr: { hook: "Lampe de bureau Bauhaus, BAG-Turgi, Suisse.", desc: "Lampe de bureau Bauhaus, BAG-Turgi, Suisse.\nModèle 4.356, conçu en 1936. Base en fonte, réflecteur en tôle d'acier avec vernis brun rétractable d'origine. Électrification d'origine, peut être renouvelée sur demande.\nH = 30 cm." },
    it: { hook: "Lampada da scrivania Bauhaus, BAG-Turgi, Svizzera.", desc: "Lampada da scrivania Bauhaus, BAG-Turgi, Svizzera.\nModello 4.356, disegnato nel 1936. Base in ghisa, riflettore in lamiera d'acciaio con vernice bruna termoretraibile originale. Elettrificazione originale, sostituibile su richiesta.\nA = 30 cm." }
  },
  43: {
    en: { hook: "Max Ingrand for Fontana Arte, circa 1950.", desc: "Max Ingrand for Fontana Arte, circa 1950. Clear cut glass with brass handle.\n11.5 x 20.5 x 14 cm." },
    fr: { hook: "Max Ingrand pour Fontana Arte, vers 1950.", desc: "Max Ingrand pour Fontana Arte, vers 1950. Verre transparent taillé avec anse en laiton.\n11,5 x 20,5 x 14 cm." },
    it: { hook: "Max Ingrand per Fontana Arte, circa 1950.", desc: "Max Ingrand per Fontana Arte, circa 1950. Vetro trasparente molato con manico in ottone.\n11,5 x 20,5 x 14 cm." }
  },
  44: {
    en: { hook: "AVEM (Arte Vetraria Muranese), circa 1955.", desc: "Anzolo Fuga.\nAVEM (Arte Vetraria Muranese), circa 1955. Monumental 50 cm (19.68 in) tall \"Bandiere\" vase. White glass with variously coloured \"A canne verticali\" glass rods." },
    fr: { hook: "AVEM (Arte Vetraria Muranese), vers 1955.", desc: "Anzolo Fuga.\nAVEM (Arte Vetraria Muranese), vers 1955. Vase \"Bandiere\" monumental de 50 cm (19,68 in) de haut. Verre blanc avec tiges de verre \"A canne verticali\" de différentes couleurs." },
    it: { hook: "AVEM (Arte Vetraria Muranese), circa 1955.", desc: "Anzolo Fuga.\nAVEM (Arte Vetraria Muranese), circa 1955. Vaso \"Bandiere\" monumentale alto 50 cm (19,68 in). Vetro bianco con canne di vetro \"A canne verticali\" di vari colori." }
  },
  45: {
    en: { hook: "Applied foot of mirrored clear glass.", desc: "Murano, circa 1932-1940. Unknown manufacturer.\nDark violet glass. Applied foot of mirrored clear glass.\nThe work is very reminiscent of the \"cristallo e argento\" or \"bianco e argento\" product line from 1932 that Tomaso Buzzi designed for Venini.\nHeight: 30 cm." },
    fr: { hook: "Pied appliqué en verre transparent argenté.", desc: "Murano, vers 1932-1940. Fabricant inconnu.\nVerre violet foncé. Pied appliqué en verre transparent argenté.\nL'œuvre rappelle beaucoup la ligne de produits \"cristallo e argento\" ou \"bianco e argento\" de 1932 que Tomaso Buzzi conçut pour Venini.\nHauteur: 30 cm." },
    it: { hook: "Piede applicato in vetro trasparente specchiato.", desc: "Murano, circa 1932-1940. Produttore sconosciuto.\nVetro viola scuro. Piede applicato in vetro trasparente specchiato.\nL'opera ricorda molto la linea di prodotti \"cristallo e argento\" o \"bianco e argento\" del 1932 che Tomaso Buzzi disegnò per Venini.\nAltezza: 30 cm." }
  },
  46: {
    en: { hook: "Design: Ercole Barovier (1889-1974), 1972.", desc: "Design: Ercole Barovier (1889-1974), 1972.\nManufacturer: Barovier & Toso.\nPear shape, with rounded, fused foot and slightly flared mouth with black rim. Colourless glass with pink fused Murrines, with black rim.\nH = 43 cm (16.92 inch).\nRef: Attilia Dorigato, Ercole Barovier 1889-1974. Venice 1989, P. 124, No. 118." },
    fr: { hook: "Conception: Ercole Barovier (1889-1974), 1972.", desc: "Conception: Ercole Barovier (1889-1974), 1972.\nFabricant: Barovier & Toso.\nForme de poire, avec pied arrondi fusionné et embouchure légèrement évasée avec bord noir. Verre incolore avec Murrines fusionnées roses, à bord noir.\nH = 43 cm (16,92 in).\nRéf: Attilia Dorigato, Ercole Barovier 1889-1974. Venise 1989, P. 124, N° 118." },
    it: { hook: "Disegno: Ercole Barovier (1889-1974), 1972.", desc: "Disegno: Ercole Barovier (1889-1974), 1972.\nProduttore: Barovier & Toso.\nForma a pera, con piede arrotondato fuso e imboccatura leggermente svasata con bordo nero. Vetro incolore con Murrine rosa fuse, con bordo nero.\nA = 43 cm (16,92 in).\nBibl: Attilia Dorigato, Ercole Barovier 1889-1974. Venezia 1989, P. 124, N. 118." }
  },
  47: {
    en: { hook: "Pear shape with applied conical foot.", desc: "Design: attributed to Ercole Barovier.\nManufacturer: attributed to Vetreria Artistica Barovier (1919-1936).\nPear shape with applied conical foot. Slightly flared mouth with two applied handles. Violet-coloured, appearing black, base glass overlaid with aventurine and clear glass.\nH = 28.5 cm." },
    fr: { hook: "Forme de poire avec pied conique appliqué.", desc: "Conception: attribuée à Ercole Barovier.\nFabricant: attribué à Vetreria Artistica Barovier (1919-1936).\nForme de poire avec pied conique appliqué. Embouchure légèrement évasée avec deux anses appliquées. Verre de base de couleur violet apparaissant noir, doublé d'aventurine et de verre transparent.\nH = 28,5 cm." },
    it: { hook: "Forma a pera con piede conico applicato.", desc: "Disegno: attribuito a Ercole Barovier.\nProduttore: attribuito a Vetreria Artistica Barovier (1919-1936).\nForma a pera con piede conico applicato. Imboccatura leggermente svasata con due manici applicati. Vetro base viola che appare nero, sovrapposto con avventurina e vetro trasparente.\nA = 28,5 cm." }
  },
  48: {
    en: { hook: "Body of violet glass appearing black, covered with aventurine.", desc: "Manufacturer: Fratelli Toso.\nBody of violet glass appearing black, covered with aventurine. Applied foot in amber-coloured glass. Applied handles in black glass.\nH = 16 cm." },
    fr: { hook: "Corps en verre violet apparaissant noir, recouvert d'aventurine.", desc: "Fabricant: Fratelli Toso.\nCorps en verre violet apparaissant noir, recouvert d'aventurine. Pied appliqué en verre ambré. Anses appliquées en verre noir.\nH = 16 cm." },
    it: { hook: "Corpo in vetro viola che appare nero, ricoperto di avventurina.", desc: "Produttore: Fratelli Toso.\nCorpo in vetro viola che appare nero, ricoperto di avventurina. Piede applicato in vetro color ambra. Manici applicati in vetro nero.\nA = 16 cm." }
  },
  49: {
    en: { hook: "Calzedonia glass with aventurine flecks.", desc: "Venice, 1st half of the 18th century.\nCalzedonia glass with aventurine flecks.\nH = 8 cm.\nReference: Museo del Vetro di Murano. Identical beakers are on display there." },
    fr: { hook: "Verre Calzedonia avec taches d'aventurine.", desc: "Venise, 1ère moitié du XVIIIe siècle.\nVerre Calzedonia avec taches d'aventurine.\nH = 8 cm.\nRéférence: Museo del Vetro di Murano. Des gobelets identiques y sont exposés." },
    it: { hook: "Vetro calcedonio con macchie di avventurina.", desc: "Venezia, 1ª metà del XVIII secolo.\nVetro calcedonio con macchie di avventurina.\nA = 8 cm.\nRiferimento: Museo del Vetro di Murano. Bicchieri identici vi sono esposti." }
  },
  50: {
    en: { hook: "Sasso vase by Luciano Gaspari (1913-2007) for Salviati & Co., 1962.", desc: "Sasso vase by Luciano Gaspari (1913-2007) for Salviati & Co., 1962. Clear glass with applied blue and green tinted glass beads. Marked on the base with diamond point: Salviati by L. Gaspari.\nH = 17 cm (6.69 in)." },
    fr: { hook: "Vase Sasso de Luciano Gaspari (1913-2007) pour Salviati & Co., 1962.", desc: "Vase Sasso de Luciano Gaspari (1913-2007) pour Salviati & Co., 1962. Verre transparent avec perles de verre teintées bleues et vertes appliquées. Marqué sur le pied à la pointe de diamant: Salviati by L. Gaspari.\nH = 17 cm (6,69 in)." },
    it: { hook: "Vaso Sasso di Luciano Gaspari (1913-2007) per Salviati & Co., 1962.", desc: "Vaso Sasso di Luciano Gaspari (1913-2007) per Salviati & Co., 1962. Vetro trasparente con perline in vetro colorato blu e verde applicate. Contrassegnato sulla base a punta di diamante: Salviati by L. Gaspari.\nA = 17 cm (6,69 in)." }
  }
});
