// PART 2 of translations - products 51-100
window.PRODUCT_TRANSLATIONS = window.PRODUCT_TRANSLATIONS || {};
Object.assign(window.PRODUCT_TRANSLATIONS, {
  51: {
    en: { hook: "Flavio Poli and Archimede Seguso for Artistica soffiera e vetreria-Barovier Seguso & Ferro, 1936.", desc: "Flavio Poli and Archimede Seguso for Artistica soffiera e vetreria-Barovier Seguso & Ferro, 1936.\nThick-walled, cylindrical Bullicante Oro Indotto perfume bottle, the inner wall sandblasted.\nH = 21.5 cm (8.26 in).\nIn 1936, Artistica soffiera e vetreria-Barovier Seguso & Ferro used the two-line etched \"Made in Italy\" stamp. In 1937 the company changed its name to Seguso vetri d'arte.\nRef: Marc Heiremans. Seguso vetri d'arte, Glass objects from Murano (1932-1973). Arnoldsche. 376 and 377." },
    fr: { hook: "Flavio Poli et Archimede Seguso pour Artistica soffiera e vetreria-Barovier Seguso & Ferro, 1936.", desc: "Flavio Poli et Archimede Seguso pour Artistica soffiera e vetreria-Barovier Seguso & Ferro, 1936.\nFlacon à parfum Bullicante Oro Indotto cylindrique à parois épaisses, la paroi intérieure sablée.\nH = 21,5 cm (8,26 in).\nEn 1936, la maison Artistica soffiera e vetreria-Barovier Seguso & Ferro utilisait le tampon gravé sur deux lignes \"Made in Italy\". En 1937, la maison changea son nom en Seguso vetri d'arte.\nRéf: Marc Heiremans. Seguso vetri d'arte, Glass objects from Murano (1932-1973). Arnoldsche. 376 et 377." },
    it: { hook: "Flavio Poli e Archimede Seguso per Artistica soffiera e vetreria-Barovier Seguso & Ferro, 1936.", desc: "Flavio Poli e Archimede Seguso per Artistica soffiera e vetreria-Barovier Seguso & Ferro, 1936.\nBottiglia da profumo Bullicante Oro Indotto cilindrica a pareti spesse, con parete interna sabbiata.\nA = 21,5 cm (8,26 in).\nNel 1936 la ditta Artistica soffiera e vetreria-Barovier Seguso & Ferro utilizzava il timbro inciso su due righe \"Made in Italy\". Nel 1937 la ditta cambiò nome in Seguso vetri d'arte.\nBibl: Marc Heiremans. Seguso vetri d'arte, Glass objects from Murano (1932-1973). Arnoldsche. 376 e 377." }
  },
  52: {
    en: { hook: "Design by Fulvio Bianconi (1915-1996), circa 1955.", desc: "Model no. 4896.\nDesign by Fulvio Bianconi (1915-1996), circa 1955.\nManufactured by Venini, Murano.\nColourless glass with vertically incorporated violet, yellow and grey stripes.\nTwo-line diamond point signature from the period 1965/66.\n14.5 x 19.5 x 15.5 cm (5.51 x 7.48 x 5.9 in).\nRef: Marino Barovier & Carla Sonego, Fulvio Bianconi alla Venini, P. 304." },
    fr: { hook: "Conception de Fulvio Bianconi (1915-1996), vers 1955.", desc: "Modèle n° 4896.\nConception de Fulvio Bianconi (1915-1996), vers 1955.\nFabriqué par Venini, Murano.\nVerre incolore avec bandes violettes, jaunes et grises incorporées verticalement.\nSignature à la pointe de diamant sur deux lignes de la période 1965/66.\n14,5 x 19,5 x 15,5 cm (5,51 x 7,48 x 5,9 in).\nRéf: Marino Barovier & Carla Sonego, Fulvio Bianconi alla Venini, P. 304." },
    it: { hook: "Disegno di Fulvio Bianconi (1915-1996), circa 1955.", desc: "Modello n. 4896.\nDisegno di Fulvio Bianconi (1915-1996), circa 1955.\nProdotto da Venini, Murano.\nVetro incolore con strisce viola, gialle e grigie incorporate verticalmente.\nFirma a punta di diamante su due righe del periodo 1965/66.\n14,5 x 19,5 x 15,5 cm (5,51 x 7,48 x 5,9 in).\nBibl: Marino Barovier & Carla Sonego, Fulvio Bianconi alla Venini, P. 304." }
  },
  53: {
    en: { hook: "Duilio Dubé Barnabé (1914-1961) and Fontana Arte, Italy, circa 1955.", desc: "Duilio Dubé Barnabé (1914-1961) and Fontana Arte, Italy, circa 1955.\nLarge glass panel with hammered edge, reverse glass painting with gold leaf. Two fighting roosters.\nSigned lower right: \"DUBÉ*FONTANA ARTE*\".\n81 x 115 cm (31.89 x 45.27 in)." },
    fr: { hook: "Duilio Dubé Barnabé (1914-1961) et Fontana Arte, Italie, vers 1955.", desc: "Duilio Dubé Barnabé (1914-1961) et Fontana Arte, Italie, vers 1955.\nGrand panneau de verre à bord martelé, peinture sous verre avec feuille d'or. Deux coqs combattant.\nSigné en bas à droite: \"DUBÉ*FONTANA ARTE*\".\n81 x 115 cm (31,89 x 45,27 in)." },
    it: { hook: "Duilio Dubé Barnabé (1914-1961) e Fontana Arte, Italia, circa 1955.", desc: "Duilio Dubé Barnabé (1914-1961) e Fontana Arte, Italia, circa 1955.\nGrande lastra di vetro con bordo martellato, pittura sotto vetro con foglia d'oro. Due galli combattenti.\nFirmato in basso a destra: \"DUBÉ*FONTANA ARTE*\".\n81 x 115 cm (31,89 x 45,27 in)." }
  },
  54: {
    en: { hook: "Clear glass body, frosted and iridescent.", desc: "\"Donna\" vase. Design by Fulvio Bianconi 1989 for Venini.\nClear glass body, frosted and iridescent.\nInscribed signature: venini 95.\nH = 47 cm (18.5 in).\nRef: Gli Artisti di Venini. Per una storia del vetro d'arte Veneziano, Electa Editori 1996, P. 172, No. 267.\nMarino Barovier con Carla Sonego; Fulvio Bianconi alla Venini; SKIRA. P. 508, Ref. No. 550.00." },
    fr: { hook: "Corps en verre transparent, dépoli et irisé.", desc: "Vase \"Donna\". Conception de Fulvio Bianconi 1989 pour Venini.\nCorps en verre transparent, dépoli et irisé.\nSignature gravée: venini 95.\nH = 47 cm (18,5 in).\nRéf: Gli Artisti di Venini. Per una storia del vetro d'arte Veneziano, Electa Editori 1996, P. 172, N° 267.\nMarino Barovier con Carla Sonego; Fulvio Bianconi alla Venini; SKIRA. P. 508, Réf. n° 550.00." },
    it: { hook: "Corpo in vetro trasparente, satinato e iridescente.", desc: "Vaso \"Donna\". Disegno di Fulvio Bianconi 1989 per Venini.\nCorpo in vetro trasparente, satinato e iridescente.\nFirma incisa: venini 95.\nA = 47 cm (18,5 in).\nBibl: Gli Artisti di Venini. Per una storia del vetro d'arte Veneziano, Electa Editori 1996, P. 172, N. 267.\nMarino Barovier con Carla Sonego; Fulvio Bianconi alla Venini; SKIRA. P. 508, Rif. n. 550.00." }
  },
  55: {
    en: { hook: "Very rare carnelian glass lamp base by Loetz Witwe, Klostermühle, Bohemia, circa 1888/89.", desc: "Very rare carnelian glass lamp base by Loetz Witwe, Klostermühle, Bohemia, circa 1888/89.\nCarnelian glass (white opal glass, cased with red-veined clear glass), gilt bronze and brass. Chip on the column, see photo.\nH = 60 cm (23.62 in)." },
    fr: { hook: "Très rare pied de lampe en verre cornaline de Loetz Witwe, Klostermühle, Bohême, vers 1888/89.", desc: "Très rare pied de lampe en verre cornaline de Loetz Witwe, Klostermühle, Bohême, vers 1888/89.\nVerre cornaline (verre opalin blanc, doublé de verre transparent veiné de rouge), bronze doré et laiton. Éclat sur la colonne, voir photo.\nH = 60 cm (23,62 in)." },
    it: { hook: "Rarissima base per lampada in vetro corniola di Loetz Witwe, Klostermühle, Boemia, circa 1888/89.", desc: "Rarissima base per lampada in vetro corniola di Loetz Witwe, Klostermühle, Boemia, circa 1888/89.\nVetro corniola (vetro opale bianco, sovrapposto con vetro trasparente venato di rosso), bronzo dorato e ottone. Scheggiatura sulla colonna, vedi foto.\nA = 60 cm (23,62 in)." }
  },
  56: {
    en: { hook: "In collaboration with Franz Pelzel (1900-1974), for S.A.L.I.R., circa 1930.", desc: "In collaboration with Franz Pelzel (1900-1974), for S.A.L.I.R. (Studio Ars Labor Industrie Riunite), circa 1930.\nCylindrical clear glass body with engraved decoration of a mermaid, abstracted waves and a star. Conical black foot. Paper label from Pauli & C. on the foot.\n33.5 cm (13 in)." },
    fr: { hook: "En collaboration avec Franz Pelzel (1900-1974), pour S.A.L.I.R., vers 1930.", desc: "En collaboration avec Franz Pelzel (1900-1974), pour S.A.L.I.R. (Studio Ars Labor Industrie Riunite), vers 1930.\nCorps cylindrique en verre transparent avec décor gravé d'une sirène, de vagues abstraites et d'une étoile. Pied conique noir. Étiquette papier de Pauli & C. sur le pied.\n33,5 cm (13 in)." },
    it: { hook: "In collaborazione con Franz Pelzel (1900-1974), per S.A.L.I.R., circa 1930.", desc: "In collaborazione con Franz Pelzel (1900-1974), per S.A.L.I.R. (Studio Ars Labor Industrie Riunite), circa 1930.\nCorpo cilindrico in vetro trasparente con decoro inciso di una sirena, onde astratte e una stella. Piede conico nero. Etichetta cartacea di Pauli & C. sul piede.\n33,5 cm (13 in)." }
  },
  57: {
    en: { hook: "Slip Graal vase in pear shape.", desc: "Design by Edward Hald.\nSlip Graal vase in pear shape. Design by Edward Hald for Orrefors 1976. Marked: Orrefors, S. Graal, No. 1967 E6.\nHeight = 23 cm." },
    fr: { hook: "Vase Slip Graal en forme de poire.", desc: "Conception d'Edward Hald.\nVase Slip Graal en forme de poire. Conception d'Edward Hald pour Orrefors 1976. Marqué: Orrefors, S. Graal, No. 1967 E6.\nHauteur = 23 cm." },
    it: { hook: "Vaso Slip Graal a forma di pera.", desc: "Disegno di Edward Hald.\nVaso Slip Graal a forma di pera. Disegno di Edward Hald per Orrefors 1976. Contrassegnato: Orrefors, S. Graal, N. 1967 E6.\nAltezza = 23 cm." }
  },
  58: {
    en: { hook: "Long-necked vase with yellow-green Murrine on clear glass.", desc: "Design by Ermanno Toso.\nMurrine vase. Design by Ermanno Toso for Fratelli Toso 1955/1960. Long-necked vase with yellow-green Murrine on clear glass.\nHeight = 28 cm.\nRef: Leslie Piña, Fratelli Toso, Italian Glass 1854-1980. A Schiffer Book. P. 50." },
    fr: { hook: "Vase à long col avec Murrine jaune-vert sur verre transparent.", desc: "Conception d'Ermanno Toso.\nVase Murrine. Conception d'Ermanno Toso pour Fratelli Toso 1955/1960. Vase à long col avec Murrine jaune-vert sur verre transparent.\nHauteur = 28 cm.\nRéf: Leslie Piña, Fratelli Toso, Italian Glass 1854-1980. A Schiffer Book. P. 50." },
    it: { hook: "Vaso a collo lungo con Murrine giallo-verdi su vetro trasparente.", desc: "Disegno di Ermanno Toso.\nVaso Murrine. Disegno di Ermanno Toso per Fratelli Toso 1955/1960. Vaso a collo lungo con Murrine giallo-verdi su vetro trasparente.\nAltezza = 28 cm.\nBibl: Leslie Piña, Fratelli Toso, Italian Glass 1854-1980. A Schiffer Book. P. 50." }
  },
  59: {
    en: { hook: "\"Canne trasversale\" bowl.", desc: "Design by Archimede Seguso.\n\"Canne trasversale\" bowl. Design by Archimede Seguso for Vetreria Archimede Seguso, circa 1955. Thick-walled cased glass with \"Zanfirico\" rods.\nRef: Marc Heiremans, Murano Glass Themes and Variations (1910-1970) P. 94. Leslie Piña, Archimede Seguso, Mid-Mod Glass from Murano, P. 85-88." },
    fr: { hook: "Coupe \"canne trasversale\".", desc: "Conception d'Archimede Seguso.\nCoupe \"canne trasversale\". Conception d'Archimede Seguso pour Vetreria Archimede Seguso, vers 1955. Verre doublé à parois épaisses avec tiges \"Zanfirico\".\nRéf: Marc Heiremans, Murano Glass Themes and Variations (1910-1970) P. 94. Leslie Piña, Archimede Seguso, Mid-Mod Glass from Murano, P. 85-88." },
    it: { hook: "Coppa \"canne trasversale\".", desc: "Disegno di Archimede Seguso.\nCoppa \"canne trasversale\". Disegno di Archimede Seguso per Vetreria Archimede Seguso, circa 1955. Vetro sovrapposto a pareti spesse con canne \"Zanfirico\".\nBibl: Marc Heiremans, Murano Glass Themes and Variations (1910-1970) P. 94. Leslie Piña, Archimede Seguso, Mid-Mod Glass from Murano, P. 85-88." }
  },
  60: {
    en: { hook: "Brass and plastic, glass with air inclusions.", desc: "Germany, circa 1960. Brass and plastic, glass with air inclusions. Inside with decorative spheres and four sockets. 53 x 40 cm." },
    fr: { hook: "Laiton et plastique, verre avec inclusions d'air.", desc: "Allemagne, vers 1960. Laiton et plastique, verre avec inclusions d'air. À l'intérieur avec sphères décoratives et quatre douilles. 53 x 40 cm." },
    it: { hook: "Ottone e plastica, vetro con inclusioni d'aria.", desc: "Germania, circa 1960. Ottone e plastica, vetro con inclusioni d'aria. All'interno con sfere decorative e quattro portalampade. 53 x 40 cm." }
  },
  61: {
    en: { hook: "Very rare bowl with two differently coloured, interworked and cut glass panes.", desc: "In vetro bicolore e molato. Design attributed to Max Ingrand for Fontana Arte, circa 1950. Very rare bowl with two differently coloured, interworked and cut glass panes.\n4 x 21 x 17.5 cm." },
    fr: { hook: "Coupe très rare avec deux panneaux de verre de couleurs différentes, entrelacés et taillés.", desc: "In vetro bicolore e molato. Conception attribuée à Max Ingrand pour Fontana Arte, vers 1950. Coupe très rare avec deux panneaux de verre de couleurs différentes, entrelacés et taillés.\n4 x 21 x 17,5 cm." },
    it: { hook: "Coppa molto rara con due lastre di vetro di colori diversi, intrecciate e molate.", desc: "In vetro bicolore e molato. Disegno attribuito a Max Ingrand per Fontana Arte, circa 1950. Coppa molto rara con due lastre di vetro di colori diversi, intrecciate e molate.\n4 x 21 x 17,5 cm." }
  },
  62: {
    en: { hook: "Executed by: Caruelle, 105 Bd Soult Paris (XII) France.", desc: "Designed circa 1930: Jean-François or Georges Albert Ulysse Caruelle (depending on the source).\nExecuted by: Caruelle, 105 Bd Soult Paris (XII) France.\nChromed metal, oak, feet with rubber.\nWith manufacturer's label.\n75 x 54 x 40 cm (29.52 x 21.25 x 15.74 in).\nThe table was designed in 1927 and went into production in Paris in 1929. In 1942, the Embru company in Rüti, Switzerland, bought the patent from Caruelle and has been producing this multifunctional table, with interruptions, until today.\nThe elaborately produced variant offered here is probably the first serially produced version." },
    fr: { hook: "Exécution: Caruelle, 105 Bd Soult Paris (XII) France.", desc: "Conception vers 1930: Jean-François ou Georges Albert Ulysse Caruelle (selon la source).\nExécution: Caruelle, 105 Bd Soult Paris (XII) France.\nMétal chromé, chêne, pieds en caoutchouc.\nAvec étiquette du fabricant.\n75 x 54 x 40 cm (29,52 x 21,25 x 15,74 in).\nLa table fut conçue en 1927 et mise en production à Paris en 1929. En 1942, la société Embru à Rüti, Suisse, acheta le brevet de la société Caruelle et produit cette table multifonctionnelle, avec interruptions, jusqu'à aujourd'hui.\nLa variante proposée ici, très soigneusement fabriquée, est probablement la première version produite en série." },
    it: { hook: "Esecuzione: Caruelle, 105 Bd Soult Paris (XII) France.", desc: "Progettato circa 1930: Jean-François o Georges Albert Ulysse Caruelle (a seconda della fonte).\nEsecuzione: Caruelle, 105 Bd Soult Paris (XII) France.\nMetallo cromato, rovere, piedi in gomma.\nCon etichetta del produttore.\n75 x 54 x 40 cm (29,52 x 21,25 x 15,74 in).\nIl tavolo fu progettato nel 1927 e messo in produzione a Parigi nel 1929. Nel 1942 la ditta Embru di Rüti, Svizzera, acquistò il brevetto dalla Caruelle e produce questo tavolo multifunzionale, con interruzioni, fino ad oggi.\nLa variante qui offerta, molto elaborata, è probabilmente la prima versione prodotta in serie." }
  },
  63: {
    en: { hook: "Caruelle table, EMBRU Werke, circa 1943.", desc: "Caruelle table, EMBRU Werke, circa 1943.\nDesign: Georges Albert Ulysse Caruelle, 1927.\nManufacturer: EMBRU Werke, Rüti, Switzerland, circa 1943.\nChromed metal, maple-veneered wood, maple. Feet in black Bakelite.\n54 x 42 cm, H max. 110 cm.\nThe table was designed in 1927 and went into production in Paris in 1929. In 1942, the Embru company in Rüti, Switzerland, bought the patent from Caruelle and has been producing this multifunctional table, with interruptions, until today." },
    fr: { hook: "Table Caruelle, EMBRU Werke, vers 1943.", desc: "Table Caruelle, EMBRU Werke, vers 1943.\nConception: Georges Albert Ulysse Caruelle, 1927.\nFabricant: EMBRU Werke, Rüti, Suisse, vers 1943.\nMétal chromé, bois plaqué érable, érable. Pieds en bakélite noire.\n54 x 42 cm, H max. 110 cm.\nLa table fut conçue en 1927 et mise en production à Paris en 1929. En 1942, la société Embru à Rüti, Suisse, acheta le brevet de la société Caruelle et produit cette table multifonctionnelle, avec interruptions, jusqu'à aujourd'hui." },
    it: { hook: "Tavolo Caruelle, EMBRU Werke, circa 1943.", desc: "Tavolo Caruelle, EMBRU Werke, circa 1943.\nDisegno: Georges Albert Ulysse Caruelle, 1927.\nProduttore: EMBRU Werke, Rüti, Svizzera, circa 1943.\nMetallo cromato, legno impiallacciato acero, acero. Piedi in bachelite nera.\n54 x 42 cm, A max. 110 cm.\nIl tavolo fu progettato nel 1927 e messo in produzione a Parigi nel 1929. Nel 1942 la ditta Embru di Rüti, Svizzera, acquistò il brevetto dalla Caruelle e produce questo tavolo multifunzionale, con interruzioni, fino ad oggi." }
  },
  64: {
    en: { hook: "Santos rosewood, glass and silvered metal.", desc: "Léon Jallot (1874-1967).\nVitrine circa 1925.\nSantos rosewood, glass and silvered metal.\nCurved front, the door made of concave curved glass, in a silvered metal frame. The legs slightly protruding and continuous to the top plate, ending at the top in a volute. Three glass shelves. Signed on the back L. Jallot.\n160 x 107 x 40 cm (63 x 42.12 x 15.74 in).\nThrough the raised legs and rounded door, the vitrine appears extremely elegant and at the same time simple.\nA matching half-cabinet (same form, construction and ornamentation) was exhibited in 1925 at \"L'Hôtel du Collectionneur\" (also called the Emile Jacques Ruhlmann Pavilion) at the \"Exposition Internationale des Arts Décoratifs et Industriels Modernes\" in Paris. Here, the Art Deco style had its beginnings.\nOther furniture by L. Jallot was also exhibited at this exhibition in the \"Pavillon de l'Ambassade Française\". Whether the vitrine was also at the exhibition eludes my knowledge.\nThe half-cabinet exhibited at the time is now in the Metropolitan Museum of Art (Met or Metmuseum) in New York (see last image).\nLéon Jallot was born in 1874 in Nantes. In 1890 - at 16 years old - he opened his atelier for sculpture and furniture in Paris. Siegfried Bing noticed him and employed him as head of the Atelier Siegfried Bing, which belonged to the Magasin de L'Art Nouveau, which gave the style its name. He stayed there until 1901, where among other things he directed the Pavillon Art Nouveau Bing at the Exposition Universelle de 1900 in Paris. In 1903 he opened his own furnishing store. His furniture and designs were exhibited among others in 1908 at the \"Salon de la Société Nationale des Beaux Arts\" and in 1919 at the \"Salon d'automne\"." },
    fr: { hook: "Palissandre Santos, verre et métal argenté.", desc: "Léon Jallot (1874-1967).\nVitrine vers 1925.\nPalissandre Santos, verre et métal argenté.\nFaçade galbée, la porte en verre bombé concave, dans un cadre en métal argenté. Les pieds légèrement saillants et continus jusqu'au plateau, se terminant en volute au sommet. Trois étagères en verre. Signée au dos L. Jallot.\n160 x 107 x 40 cm (63 x 42,12 x 15,74 in).\nGrâce aux pieds surélevés et à la porte arrondie, la vitrine apparaît extrêmement élégante et à la fois sobre.\nUn demi-meuble assorti à cette vitrine (même forme, construction et ornementation) fut exposé en 1925 à \"L'Hôtel du Collectionneur\" (également appelé Pavillon Emile Jacques Ruhlmann) à l'\"Exposition Internationale des Arts Décoratifs et Industriels Modernes\" à Paris. C'est là que le style Art Déco vit le jour.\nD'autres meubles de L. Jallot furent également exposés à cette exposition dans le \"Pavillon de l'Ambassade Française\". Si la vitrine était aussi à l'exposition m'échappe.\nLe demi-meuble alors exposé se trouve aujourd'hui au Metropolitan Museum of Art (Met ou Metmuseum) à New York (voir dernière image).\nLéon Jallot est né en 1874 à Nantes. En 1890 - à 16 ans - il ouvrit son atelier de sculpture et de mobilier à Paris. Siegfried Bing le remarqua et l'engagea comme directeur de l'Atelier Siegfried Bing, appartenant au Magasin de L'Art Nouveau, qui donna son nom au style. Il y resta jusqu'en 1901, où il dirigea entre autres le Pavillon Art Nouveau Bing à l'Exposition Universelle de 1900 à Paris. En 1903, il ouvrit sa propre boutique d'ameublement. Ses meubles et créations furent exposés entre autres en 1908 au \"Salon de la Société Nationale des Beaux Arts\" et en 1919 au \"Salon d'automne\"." },
    it: { hook: "Palissandro Santos, vetro e metallo argentato.", desc: "Léon Jallot (1874-1967).\nVetrina circa 1925.\nPalissandro Santos, vetro e metallo argentato.\nFronte curvo, l'anta in vetro curvato concavo, in una cornice di metallo argentato. Le gambe leggermente sporgenti e continue fino al piano, terminanti in alto con una voluta. Tre ripiani in vetro. Firmata sul retro L. Jallot.\n160 x 107 x 40 cm (63 x 42,12 x 15,74 in).\nGrazie alle gambe rialzate e all'anta arrotondata, la vetrina appare estremamente elegante e allo stesso tempo sobria.\nUn mezzo mobile abbinato a questa vetrina (stessa forma, costruzione e ornamentazione) fu esposto nel 1925 a \"L'Hôtel du Collectionneur\" (chiamato anche Padiglione Emile Jacques Ruhlmann) all'\"Exposition Internationale des Arts Décoratifs et Industriels Modernes\" di Parigi. Fu qui che nacque lo stile Art Déco.\nAltri mobili di L. Jallot furono esposti a questa mostra anche nel \"Pavillon de l'Ambassade Française\". Non so se anche la vetrina fosse alla mostra.\nIl mezzo mobile allora esposto si trova oggi al Metropolitan Museum of Art (Met o Metmuseum) di New York (vedi ultima immagine).\nLéon Jallot nacque nel 1874 a Nantes. Nel 1890 - a 16 anni - aprì il suo atelier di scultura e mobili a Parigi. Siegfried Bing lo notò e lo assunse come direttore dell'Atelier Siegfried Bing, che apparteneva al Magasin de L'Art Nouveau, che diede il nome allo stile. Vi rimase fino al 1901, dove tra l'altro diresse il Padiglione Art Nouveau Bing all'Esposizione Universale del 1900 a Parigi. Nel 1903 aprì il proprio negozio di arredamento. I suoi mobili e disegni furono esposti tra l'altro nel 1908 al \"Salon de la Société Nationale des Beaux Arts\" e nel 1919 al \"Salon d'automne\"." }
  },
  65: {
    en: { hook: "Variant with rectangular table top.", desc: "Bauhaus table model no. MR 515.\nVariant with rectangular table top.\nDesign: Ludwig Mies van der Rohe, circa 1930.\nManufacturer: Bigla, Biglen near Bern, Switzerland.\n61 x 65 x 65 cm (24 x 25.59 x 25.59 in). Table top: 61 x 61 cm (25.59 x 25.59 in).\nChromed tubular steel, black-lacquered wood with black-tinted glass top. Rubber feet.\nLiterature:\n- Werner Blaser, Mies van der Rohe – Möbel und Interieurs, Deutsche Verlags-Anstalt 1981. P. 43. Ill. 103.\n- Alexander von Vegesack. Deutsche Stahlrohr Möbel, Bangert Verlag, Munich, 1986, P. 114." },
    fr: { hook: "Variante avec plateau rectangulaire.", desc: "Table Bauhaus modèle n° MR 515.\nVariante avec plateau rectangulaire.\nConception: Ludwig Mies van der Rohe, vers 1930.\nFabricant: Bigla, Biglen près de Berne, Suisse.\n61 x 65 x 65 cm (24 x 25,59 x 25,59 in). Plateau: 61 x 61 cm (25,59 x 25,59 in).\nTube d'acier chromé, bois laqué noir avec plateau en verre teinté noir. Patins en caoutchouc.\nLittérature:\n- Werner Blaser, Mies van der Rohe – Möbel und Interieurs, Deutsche Verlags-Anstalt 1981. P. 43. Ill. 103.\n- Alexander von Vegesack. Deutsche Stahlrohr Möbel, Bangert Verlag, Munich, 1986, P. 114." },
    it: { hook: "Variante con piano rettangolare.", desc: "Tavolo Bauhaus modello n. MR 515.\nVariante con piano rettangolare.\nDisegno: Ludwig Mies van der Rohe, circa 1930.\nProduttore: Bigla, Biglen vicino Berna, Svizzera.\n61 x 65 x 65 cm (24 x 25,59 x 25,59 in). Piano: 61 x 61 cm (25,59 x 25,59 in).\nTubo d'acciaio cromato, legno laccato nero con piano in vetro colorato nero. Piedini in gomma.\nLetteratura:\n- Werner Blaser, Mies van der Rohe – Möbel und Interieurs, Deutsche Verlags-Anstalt 1981. P. 43. Ill. 103.\n- Alexander von Vegesack. Deutsche Stahlrohr Möbel, Bangert Verlag, Monaco, 1986, P. 114." }
  },
  66: {
    en: { hook: "6 shovel chairs, Biedermeier, Vienna circa 1820/30.", desc: "6 shovel chairs, Biedermeier, Vienna circa 1820/30.\nSolid walnut and veneer. Loose newly upholstered seats, restored condition.\n6 shovel chairs, Biedermeier, Vienna around 1820/30, attributed to Josef Ulrich Danhauser.\nAccording to Austria-Lexikon, this design is said to originate from the Viennese furniture manufacturer Josef Ulrich Danhauser (1780-1829)." },
    fr: { hook: "6 chaises pelle, Biedermeier, Vienne vers 1820/30.", desc: "6 chaises pelle, Biedermeier, Vienne vers 1820/30.\nNoyer massif et plaqué. Sièges nouvellement retapissés amovibles, état restauré.\n6 chaises pelle, Biedermeier, Vienne vers 1820/30, attribuées à Josef Ulrich Danhauser.\nSelon Austria-Lexikon, cette conception proviendrait du fabricant de meubles viennois Josef Ulrich Danhauser (1780-1829)." },
    it: { hook: "6 sedie a pala, Biedermeier, Vienna circa 1820/30.", desc: "6 sedie a pala, Biedermeier, Vienna circa 1820/30.\nNoce massello e impiallacciato. Sedute nuovamente tappezzate amovibili, stato restaurato.\n6 sedie a pala, Biedermeier, Vienna intorno al 1820/30, attribuite a Josef Ulrich Danhauser.\nSecondo Austria-Lexikon, questo disegno proverebbe dal fabbricante di mobili viennese Josef Ulrich Danhauser (1780-1829)." }
  },
  67: {
    en: { hook: "A pair of consoles, Louis XV, France, circa 1760.", desc: "A pair of consoles, Louis XV, France, circa 1760. Openwork carved and gilt oak. Red-veined marble.\n83 x 81 x 33 cm.\nA pair of consoles, Louis XV, France around 1760. Carved and gilded oak with a red marble top." },
    fr: { hook: "Une paire de consoles, Louis XV, France, vers 1760.", desc: "Une paire de consoles, Louis XV, France, vers 1760. Chêne ajouré sculpté et doré. Marbre veiné rouge.\n83 x 81 x 33 cm.\nUne paire de consoles, Louis XV, France vers 1760. Chêne sculpté et doré avec plateau en marbre rouge." },
    it: { hook: "Una coppia di consoles, Luigi XV, Francia, circa 1760.", desc: "Una coppia di consoles, Luigi XV, Francia, circa 1760. Rovere traforato intagliato e dorato. Marmo venato rosso.\n83 x 81 x 33 cm.\nUna coppia di consoles, Luigi XV, Francia circa 1760. Rovere intagliato e dorato con piano in marmo rosso." }
  },
  68: {
    en: { hook: "Art Deco bistro table Thonet, France.", desc: "Art Deco bistro table Thonet, France.\nCast iron black lacquered, with a Bakelite top by Rex. The table resembles the Louis Vuitton table, which bears the LV monogram and which also has an original Rex top.\n75 x 30 cm." },
    fr: { hook: "Table de bistro Art Déco Thonet, France.", desc: "Table de bistro Art Déco Thonet, France.\nFonte laquée noire, avec un plateau en Bakélite de la maison Rex. La table ressemble à la table Louis Vuitton, qui porte le monogramme LV et qui a également à l'origine un plateau de la maison Rex.\n75 x 30 cm." },
    it: { hook: "Tavolo da bistrò Art Deco Thonet, Francia.", desc: "Tavolo da bistrò Art Deco Thonet, Francia.\nGhisa laccata nera, con un piano in bachelite della ditta Rex. Il tavolo assomiglia al tavolo Louis Vuitton, che porta il monogramma LV e che ha anch'esso in originale un piano della ditta Rex.\n75 x 30 cm." }
  },
  69: {
    en: { hook: "Albert-Ernest Carrier-Belleuse.", desc: "Albert-Ernest Carrier-Belleuse.\nVariation of the Warwick Vase, France, 2nd half of the 19th century. Gilt bronze (ormolu) and onyx. Signed on the base: Carrier-Belleuse.\n34 cm (13.38 in) high x 45 cm (17.71 in) wide." },
    fr: { hook: "Albert-Ernest Carrier-Belleuse.", desc: "Albert-Ernest Carrier-Belleuse.\nVariation du Vase de Warwick, France, 2ème moitié du XIXe siècle. Bronze doré (ormolu) et onyx. Signé sur le socle: Carrier-Belleuse.\n34 cm (13,38 in) de haut x 45 cm (17,71 in) de large." },
    it: { hook: "Albert-Ernest Carrier-Belleuse.", desc: "Albert-Ernest Carrier-Belleuse.\nVariazione del Vaso di Warwick, Francia, 2ª metà del XIX secolo. Bronzo dorato (ormolu) e onice. Firmato sulla base: Carrier-Belleuse.\n34 cm (13,38 in) di altezza x 45 cm (17,71 in) di larghezza." }
  },
  70: {
    en: { hook: "Manufacture Nationale de Sèvres.", desc: "Sèvres vase from 1930.\nManufacture Nationale de Sèvres.\nHard porcelain. Turquoise ground with running oxblood glaze (sang de boeuf). Base with copper mount. Green underglaze stamp mark. This mark was in use from 1928 to 1940. The lowercase letters indicate the year: a for 1928 / b for 1929 / c for 1930 / etc.\nHeight = 58 cm." },
    fr: { hook: "Manufacture Nationale de Sèvres.", desc: "Vase Sèvres de 1930.\nManufacture Nationale de Sèvres.\nPorcelaine dure. Fond turquoise avec émail sang de bœuf coulant. Le pied avec monture en cuivre. Marque au tampon verte sous glaçure. Cette marque fut utilisée de 1928 à 1940. Les lettres minuscules désignent l'année: a pour 1928 / b pour 1929 / c pour 1930 / etc.\nHauteur = 58 cm." },
    it: { hook: "Manufacture Nationale de Sèvres.", desc: "Vaso Sèvres del 1930.\nManufacture Nationale de Sèvres.\nPorcellana dura. Fondo turchese con smalto sangue di bue (sang de boeuf) colante. La base con montatura in rame. Marchio verde sotto vetrina. Questo marchio fu in uso dal 1928 al 1940. Le lettere minuscole indicano l'anno: a per 1928 / b per 1929 / c per 1930 / ecc.\nAltezza = 58 cm." }
  },
  71: {
    en: { hook: "Aldo Londi & Bitossi Ceramiche, Italy, circa 1960.", desc: "Aldo Londi & Bitossi Ceramiche, Italy, circa 1960.\nCeramic with blue glaze.\nVase H = 18 cm (7.08 in). Bowl D = 31.7 cm (12.2 in).\nAldo Londi (1911-2003) became artistic director of the ceramics company Bitossi in Montelupo after the Second World War. There he designed the Rimini Blue collection between 1955 and 1965. Our vase and bowl are from this series.\nAldo Londi worked with many well-known architects and designers, including Ettore Sottsass (1917-2007) from 1958, Piero Fornasetti (1913-1988), Matteo Thun (born 1952), Karim Rashid (born 1960), and many others." },
    fr: { hook: "Aldo Londi & Bitossi Ceramiche, Italie, vers 1960.", desc: "Aldo Londi & Bitossi Ceramiche, Italie, vers 1960.\nCéramique émaillée bleue.\nVase H = 18 cm (7,08 in). Coupe D = 31,7 cm (12,2 in).\nAldo Londi (1911-2003) devint directeur artistique de la société de céramique Bitossi à Montelupo après la Seconde Guerre mondiale. Il y conçut la collection Rimini Blue entre 1955 et 1965. Notre vase et notre coupe proviennent de cette série.\nAldo Londi collabora avec de nombreux architectes et designers renommés, notamment Ettore Sottsass (1917-2007) à partir de 1958, Piero Fornasetti (1913-1988), Matteo Thun (né en 1952), Karim Rashid (né en 1960), et bien d'autres." },
    it: { hook: "Aldo Londi & Bitossi Ceramiche, Italia, circa 1960.", desc: "Aldo Londi & Bitossi Ceramiche, Italia, circa 1960.\nCeramica smaltata blu.\nVaso A = 18 cm (7,08 in). Coppa D = 31,7 cm (12,2 in).\nAldo Londi (1911-2003) divenne direttore artistico della ditta di ceramica Bitossi di Montelupo dopo la Seconda Guerra Mondiale. Lì disegnò la collezione Rimini Blue tra il 1955 e il 1965. Il nostro vaso e la nostra coppa provengono da questa serie.\nAldo Londi collaborò con molti architetti e designer noti, tra cui Ettore Sottsass (1917-2007) dal 1958, Piero Fornasetti (1913-1988), Matteo Thun (nato nel 1952), Karim Rashid (nato nel 1960), e molti altri." }
  },
  72: {
    en: { hook: "Soleil Les Cyclades, Andus.", desc: "Soleil Les Cyclades, Andus.\nCeramic with underglaze painting.\nD = 49 cm.\nCeramic sun, artisanal creation Poterie la draille, model created by Roland Zobel, Poterie les Cyclades, circa 1960-1970." },
    fr: { hook: "Soleil Les Cyclades, Andus.", desc: "Soleil Les Cyclades, Andus.\nCéramique avec peinture sous glaçure.\nD = 49 cm.\nSoleil en céramique, création artisanale Poterie la draille, modèle créé par Roland Zobel, Poterie les Cyclades, vers 1960-1970." },
    it: { hook: "Soleil Les Cyclades, Andus.", desc: "Soleil Les Cyclades, Andus.\nCeramica con pittura sotto vetrina.\nD = 49 cm.\nSole in ceramica, creazione artigianale Poterie la draille, modello creato da Roland Zobel, Poterie les Cyclades, circa 1960-1970." }
  },
  73: {
    en: { hook: "Painted ceramic plate.", desc: "Painted ceramic plate.\nD = 28 cm." },
    fr: { hook: "Assiette en céramique peinte.", desc: "Assiette en céramique peinte.\nD = 28 cm." },
    it: { hook: "Piatto in ceramica dipinto.", desc: "Piatto in ceramica dipinto.\nD = 28 cm." }
  },
  74: {
    en: { hook: "Two ceramic plates.", desc: "Two ceramic plates.\nD = 25 cm each." },
    fr: { hook: "Deux assiettes en céramique.", desc: "Deux assiettes en céramique.\nD = 25 cm chacune." },
    it: { hook: "Due piatti in ceramica.", desc: "Due piatti in ceramica.\nD = 25 cm ciascuno." }
  },
  75: {
    en: { hook: "Manufactured by Densa Basel, 1998.", desc: "Plastic chair after a design by Verner Panton. Manufactured by Densa Basel, 1998.\nMarked: Verner Panton, Innovation Randers, Denmark." },
    fr: { hook: "Fabriqué par Densa Bâle, 1998.", desc: "Chaise en plastique d'après un dessin de Verner Panton. Fabriquée par Densa Bâle, 1998.\nMarquée: Verner Panton, Innovation Randers, Danemark." },
    it: { hook: "Prodotto da Densa Basilea, 1998.", desc: "Sedia in plastica da un disegno di Verner Panton. Prodotta da Densa Basilea, 1998.\nContrassegnata: Verner Panton, Innovation Randers, Danimarca." }
  },
  76: {
    en: { hook: "Paperweight with flower motif in the centre.", desc: "Paperweight with flower motif in the centre. Faceted crystal glass. Monogrammed \"SL\" and dated 1970.\nH = 5 cm, D = 5.5 cm." },
    fr: { hook: "Presse-papier avec motif floral au centre.", desc: "Presse-papier avec motif floral au centre. Verre cristal facetté. Monogrammé \"SL\" et daté 1970.\nH = 5 cm, D = 5,5 cm." },
    it: { hook: "Fermacarte con motivo floreale al centro.", desc: "Fermacarte con motivo floreale al centro. Vetro cristallo sfaccettato. Monogrammato \"SL\" e datato 1970.\nA = 5 cm, D = 5,5 cm." }
  },
  77: {
    en: { hook: "\"Irish Setter\" umbrella stand by Piero Fornasetti (1913-1988), Milan, circa 1955.", desc: "\"Irish Setter\" umbrella stand by Piero Fornasetti (1913-1988), Milan, circa 1955. Metal, lithographed and lacquered. Slightly restored.\n81 x 40 x 22 cm." },
    fr: { hook: "Porte-parapluies \"Irish Setter\" de Piero Fornasetti (1913-1988), Milan, vers 1955.", desc: "Porte-parapluies \"Irish Setter\" de Piero Fornasetti (1913-1988), Milan, vers 1955. Métal, lithographié et laqué. Légèrement restauré.\n81 x 40 x 22 cm." },
    it: { hook: "Portaombrelli \"Irish Setter\" di Piero Fornasetti (1913-1988), Milano, circa 1955.", desc: "Portaombrelli \"Irish Setter\" di Piero Fornasetti (1913-1988), Milano, circa 1955. Metallo, litografato e verniciato. Leggermente restaurato.\n81 x 40 x 22 cm." }
  },
  78: {
    en: { hook: "Metal lithographed and lacquered.", desc: "\"Ombrelli\" umbrella stand by Piero Fornasetti (1913-1988). Design circa 1950. Executed circa 1990. Metal, lithographed and lacquered. Slight damage, drip tray missing.\n80 x 40 x 22 cm." },
    fr: { hook: "Métal lithographié et laqué.", desc: "Porte-parapluies \"Ombrelli\" de Piero Fornasetti (1913-1988). Conception vers 1950. Exécution vers 1990. Métal, lithographié et laqué. Légers dommages, coupelle égouttoir manquante.\n80 x 40 x 22 cm." },
    it: { hook: "Metallo litografato e verniciato.", desc: "Portaombrelli \"Ombrelli\" di Piero Fornasetti (1913-1988). Disegno circa 1950. Esecuzione circa 1990. Metallo, litografato e verniciato. Lievi danni, vaschetta raccogli gocce mancante.\n80 x 40 x 22 cm." }
  },
  79: {
    en: { hook: "Table lamp for Venini, circa 1930.", desc: "Table lamp for Venini, circa 1930. H = 41 cm.\nRef: Marino Barovier, Skira Verlag 2013. Napoleone Martinuzzi / Venini 1925-1931. P. 410, No. 9016." },
    fr: { hook: "Lampe de table pour Venini, vers 1930.", desc: "Lampe de table pour Venini, vers 1930. H = 41 cm.\nRéf: Marino Barovier, Skira Verlag 2013. Napoleone Martinuzzi / Venini 1925-1931. P. 410, N° 9016." },
    it: { hook: "Lampada da tavolo per Venini, circa 1930.", desc: "Lampada da tavolo per Venini, circa 1930. A = 41 cm.\nBibl: Marino Barovier, Skira Verlag 2013. Napoleone Martinuzzi / Venini 1925-1931. P. 410, N. 9016." }
  },
  80: {
    en: { hook: "Large painted ceramic plate.", desc: "Large painted ceramic plate. Monogrammed G. P.\n8.5 x 42 cm." },
    fr: { hook: "Grande plaque en céramique peinte.", desc: "Grande plaque en céramique peinte. Monogrammée G. P.\n8,5 x 42 cm." },
    it: { hook: "Grande piatto in ceramica dipinto.", desc: "Grande piatto in ceramica dipinto. Monogrammato G. P.\n8,5 x 42 cm." }
  },
  81: {
    en: { hook: "Metal with brown patina and opal glass shades.", desc: "Circa 1930. Metal with brown patina and opal glass shades.\n45 x 28 cm.\n(without extension)" },
    fr: { hook: "Métal patiné brun avec abat-jours en verre opalin.", desc: "Vers 1930. Métal patiné brun avec abat-jours en verre opalin.\n45 x 28 cm.\n(sans rallonge)" },
    it: { hook: "Metallo patinato marrone con paralumi in vetro opale.", desc: "Circa 1930. Metallo patinato marrone con paralumi in vetro opale.\n45 x 28 cm.\n(senza prolunga)" }
  },
  82: {
    en: { hook: "Large \"Fish Mouth\" vase by Thomas Porzellan, Germany, 1957.", desc: "Large \"Fish Mouth\" vase by Thomas Porzellan, Germany, 1957.\nDesign: Raymond Loewy.\nPorcelain with grey and gold-coloured speckling." },
    fr: { hook: "Grand vase \"Gueule de poisson\" de Thomas Porzellan, Allemagne, 1957.", desc: "Grand vase \"Gueule de poisson\" de Thomas Porzellan, Allemagne, 1957.\nConception: Raymond Loewy.\nPorcelaine avec mouchetures grises et dorées." },
    it: { hook: "Grande vaso \"Bocca di Pesce\" di Thomas Porzellan, Germania, 1957.", desc: "Grande vaso \"Bocca di Pesce\" di Thomas Porzellan, Germania, 1957.\nDisegno: Raymond Loewy.\nPorcellana con macchiettature grigie e dorate." }
  },
  83: {
    en: { hook: "Glass sphere in \"Filigrana doppia\" technique.", desc: "\"Reticello\" globe lamp, 1930s, attributed to Venini.\nGlass sphere in \"Filigrana doppia\" technique. The metal parts in aluminium and chrome-plated copper.\nDiameter of the sphere 25 cm.\nRef: \"Le Catalogo blu\" by Venini from the 1930s (see illustration).\nA Venini Reticello globe lamp from the 1930s. The hardware in aluminium and chromed copper. The diameter of the globe is 9.8 inches." },
    fr: { hook: "Sphère en verre en technique \"Filigrana doppia\".", desc: "Lampe globe \"Reticello\", années 1930, attribuée à Venini.\nSphère en verre en technique \"Filigrana doppia\". Les parties métalliques en aluminium et cuivre chromé.\nDiamètre de la sphère 25 cm.\nRéf: \"Le Catalogo blu\" de Venini des années 30 (voir illustration).\nLampe globe Venini Reticello des années 1930. La quincaillerie en aluminium et cuivre chromé. Le diamètre du globe est de 9,8 pouces." },
    it: { hook: "Sfera di vetro in tecnica \"Filigrana doppia\".", desc: "Lampada globo \"Reticello\", anni '30, attribuita a Venini.\nSfera di vetro in tecnica \"Filigrana doppia\". Le parti metalliche in alluminio e rame cromato.\nDiametro della sfera 25 cm.\nBibl: \"Le Catalogo blu\" di Venini degli anni '30 (vedi illustrazione).\nLampada globo Venini Reticello degli anni '30. La componentistica in alluminio e rame cromato. Il diametro del globo è di 9,8 pollici." }
  },
  84: {
    en: { hook: "Olérys-Laugier Cadel / Moustiers bowl.", desc: "Olérys-Laugier Cadel / Moustiers bowl. Samson manufactory, 19th century after Olérys-Laugier Cadel, Moustiers 18th century. Ceramic painted with flowers and landscape scenes. Among other things with an elephant. Curved shape on dolphin feet. Slight damage.\n18 x 50 x 25 cm." },
    fr: { hook: "Coupe Olérys-Laugier Cadel / Moustiers.", desc: "Coupe Olérys-Laugier Cadel / Moustiers. Manufacture Samson, XIXe siècle d'après Olérys-Laugier Cadel, Moustiers XVIIIe siècle. Céramique peinte avec fleurs et scènes de paysages. Entre autres avec un éléphant. Forme galbée sur pieds de dauphin. Légers dommages.\n18 x 50 x 25 cm." },
    it: { hook: "Ciotola Olérys-Laugier Cadel / Moustiers.", desc: "Ciotola Olérys-Laugier Cadel / Moustiers. Manifattura Samson, XIX secolo secondo Olérys-Laugier Cadel, Moustiers XVIII secolo. Ceramica dipinta con fiori e scene paesaggistiche. Tra l'altro con un elefante. Forma curva su piedi a delfino. Lievi danni.\n18 x 50 x 25 cm." }
  },
  85: {
    en: { hook: "\"Poliedri\" chandelier by Carlo Scarpa (1906-1978) for Venini, circa 1960.", desc: "\"Poliedri\" chandelier by Carlo Scarpa (1906-1978) for Venini, circa 1960.\n32 x 37 cm.\n1960s \"Poliedri\" chandelier lamp by Carlo Scarpa (1906-1978) for Venini circa 1960.\n12.59 x 14.56 in." },
    fr: { hook: "Lustre \"Poliedri\" de Carlo Scarpa (1906-1978) pour Venini, vers 1960.", desc: "Lustre \"Poliedri\" de Carlo Scarpa (1906-1978) pour Venini, vers 1960.\n32 x 37 cm.\nLustre \"Poliedri\" des années 1960 par Carlo Scarpa (1906-1978) pour Venini vers 1960.\n12,59 x 14,56 in." },
    it: { hook: "Lampadario \"Poliedri\" di Carlo Scarpa (1906-1978) per Venini, circa 1960.", desc: "Lampadario \"Poliedri\" di Carlo Scarpa (1906-1978) per Venini, circa 1960.\n32 x 37 cm.\nLampadario \"Poliedri\" degli anni '60 di Carlo Scarpa (1906-1978) per Venini circa 1960.\n12,59 x 14,56 in." }
  },
  86: {
    en: { hook: "Red-green Corroso vase, model no. 4101.", desc: "Red-green Corroso vase, model no. 4101. Design 1936-1938.\nH = 21 cm.\n\"Vaso in vetro corroso rubino et verde con bugne applicate e superficie iridata.\"\nThis model, however only monochrome, was exhibited at the VI Triennale 1936 in Milan.\nOur vase is a rare bicolour version.\nTwo-line etched signature.\nRef: Marino Barovier, Skira 2012, CARLO SCARPA VENINI 1932-1947, P. 214.\nAnna Venini Dias de Santillana, Skira 2000, Venini, Catalogo ragionato 1921-1986, P. 141.\nMarino Barovier, Skira 1999, Carlo Scarpa Glass of an Architect, P. 125 and 211." },
    fr: { hook: "Vase Corroso rouge-vert, modèle n° 4101.", desc: "Vase Corroso rouge-vert, modèle n° 4101. Conception 1936-1938.\nH = 21 cm.\n\"Vaso in vetro corroso rubino et verde con bugne applicate e superficie iridata.\"\nCe modèle, cependant uniquement monochrome, fut exposé à la VI Triennale de Milan en 1936.\nNotre vase est une rare version bicolore.\nSignature gravée sur deux lignes.\nRéf: Marino Barovier, Skira 2012, CARLO SCARPA VENINI 1932-1947, P. 214.\nAnna Venini Dias de Santillana, Skira 2000, Venini, Catalogo ragionato 1921-1986, P. 141.\nMarino Barovier, Skira 1999, Carlo Scarpa Glass of an Architect, P. 125 et 211." },
    it: { hook: "Vaso Corroso rosso-verde, modello n. 4101.", desc: "Vaso Corroso rosso-verde, modello n. 4101. Disegno 1936-1938.\nA = 21 cm.\n\"Vaso in vetro corroso rubino et verde con bugne applicate e superficie iridata.\"\nQuesto modello, tuttavia solo monocromo, fu esposto alla VI Triennale del 1936 a Milano.\nIl nostro vaso è una rara versione bicolore.\nFirma incisa su due righe.\nBibl: Marino Barovier, Skira 2012, CARLO SCARPA VENINI 1932-1947, P. 214.\nAnna Venini Dias de Santillana, Skira 2000, Venini, Catalogo ragionato 1921-1986, P. 141.\nMarino Barovier, Skira 1999, Carlo Scarpa Glass of an Architect, P. 125 e 211." }
  },
  87: {
    en: { hook: "Clear glass fruit bowl by Andries Dirk Copier for Glasfabriek Leerdam, Holland.", desc: "Clear glass fruit bowl by Andries Dirk Copier for Glasfabriek Leerdam, Holland. Etched monogram signature LC on the base.\n8.5 x 34 cm.\nFruit bowl by Andries Dirk Copier for Glasfabriek Leerdam, Dutch. Etched monogram signature LC." },
    fr: { hook: "Coupe à fruits en verre transparent d'Andries Dirk Copier pour Glasfabriek Leerdam, Hollande.", desc: "Coupe à fruits en verre transparent d'Andries Dirk Copier pour Glasfabriek Leerdam, Hollande. Signature monogramme LC gravée sur le pied.\n8,5 x 34 cm.\nCoupe à fruits d'Andries Dirk Copier pour Glasfabriek Leerdam, Pays-Bas. Signature monogramme LC gravée." },
    it: { hook: "Coppa portafrutta in vetro trasparente di Andries Dirk Copier per Glasfabriek Leerdam, Olanda.", desc: "Coppa portafrutta in vetro trasparente di Andries Dirk Copier per Glasfabriek Leerdam, Olanda. Firma monogramma LC incisa sulla base.\n8,5 x 34 cm.\nCoppa portafrutta di Andries Dirk Copier per Glasfabriek Leerdam, Olanda. Firma monogramma LC incisa." }
  },
  88: {
    en: { hook: "Design by Max Ingrand for Fontana Arte, circa 1960.", desc: "Design by Max Ingrand for Fontana Arte, circa 1960. Brass and smoked glass.\n57 x 26 x 18 cm." },
    fr: { hook: "Conception de Max Ingrand pour Fontana Arte, vers 1960.", desc: "Conception de Max Ingrand pour Fontana Arte, vers 1960. Laiton et verre fumé.\n57 x 26 x 18 cm." },
    it: { hook: "Disegno di Max Ingrand per Fontana Arte, circa 1960.", desc: "Disegno di Max Ingrand per Fontana Arte, circa 1960. Ottone e vetro fumé.\n57 x 26 x 18 cm." }
  },
  89: {
    en: { hook: "Table lamp in Sommerso technique \"grigio cristallo\" by Seguso Vetri d'Arte, circa 1970.", desc: "Table lamp in Sommerso technique \"grigio cristallo\" by Seguso Vetri d'Arte, circa 1970. On the base with diamond point signature \"Seguso v. d'Arte\". Overall height: 42 cm. Lamp base height: 24 cm.\nTable lamp in sommerso technique \"grigio cristallo\" by Seguso Vetri d'Arte, Murano, 1970. Signed on the base \"Seguso v. d'Arte\"." },
    fr: { hook: "Lampe de table en technique Sommerso \"grigio cristallo\" de Seguso Vetri d'Arte, vers 1970.", desc: "Lampe de table en technique Sommerso \"grigio cristallo\" de Seguso Vetri d'Arte, vers 1970. Sur le pied signature à la pointe de diamant \"Seguso v. d'Arte\". Hauteur totale: 42 cm. Hauteur du pied de lampe: 24 cm.\nLampe de table en technique sommerso \"grigio cristallo\" par Seguso Vetri d'Arte, Murano, 1970. Signée sur le pied \"Seguso v. d'Arte\"." },
    it: { hook: "Lampada da tavolo in tecnica Sommerso \"grigio cristallo\" di Seguso Vetri d'Arte, circa 1970.", desc: "Lampada da tavolo in tecnica Sommerso \"grigio cristallo\" di Seguso Vetri d'Arte, circa 1970. Sulla base firma a punta di diamante \"Seguso v. d'Arte\". Altezza totale: 42 cm. Altezza base della lampada: 24 cm.\nLampada da tavolo in tecnica sommerso \"grigio cristallo\" di Seguso Vetri d'Arte, Murano, 1970. Firmata sulla base \"Seguso v. d'Arte\"." }
  },
  90: {
    en: { hook: "Early Bauhaus / Werkbund chandelier by Siemens-Schuckert-Werke (SSW) after a design by Peter Behrens, circa 1920.", desc: "Early Bauhaus / Werkbund chandelier by Siemens-Schuckert-Werke (SSW) after a design by Peter Behrens, circa 1920. Model L52. L = 130 cm (the chain can be shortened). D = 24 cm." },
    fr: { hook: "Ancien lustre Bauhaus / Werkbund de Siemens-Schuckert-Werke (SSW) d'après un dessin de Peter Behrens, vers 1920.", desc: "Ancien lustre Bauhaus / Werkbund de Siemens-Schuckert-Werke (SSW) d'après un dessin de Peter Behrens, vers 1920. Modèle L52. L = 130 cm (la chaîne peut être raccourcie). D = 24 cm." },
    it: { hook: "Antico lampadario Bauhaus / Werkbund di Siemens-Schuckert-Werke (SSW) da un disegno di Peter Behrens, circa 1920.", desc: "Antico lampadario Bauhaus / Werkbund di Siemens-Schuckert-Werke (SSW) da un disegno di Peter Behrens, circa 1920. Modello L52. L = 130 cm (la catena può essere accorciata). D = 24 cm." }
  },
  91: {
    en: { hook: "Coffee table by Severin Hansen and Nils Thorsen.", desc: "Coffee table by Severin Hansen and Nils Thorsen. Manufactured by Royal Copenhagen & Haslev Modelsnedkeri, Denmark, circa 1960.\nRosewood and ceramic.\n50 x 113 x 75 cm." },
    fr: { hook: "Table basse de Severin Hansen et Nils Thorsen.", desc: "Table basse de Severin Hansen et Nils Thorsen. Fabriquée par Royal Copenhagen & Haslev Modelsnedkeri, Danemark, vers 1960.\nPalissandre et céramique.\n50 x 113 x 75 cm." },
    it: { hook: "Tavolino da caffè di Severin Hansen e Nils Thorsen.", desc: "Tavolino da caffè di Severin Hansen e Nils Thorsen. Prodotto da Royal Copenhagen & Haslev Modelsnedkeri, Danimarca, circa 1960.\nPalissandro e ceramica.\n50 x 113 x 75 cm." }
  },
  92: {
    en: { hook: "Period 1939-1950 in verde mare oro indotto technique. Design: Flavio Poli 1939/1942.", desc: "Period 1939-1950 in verde mare oro indotto technique. Design: Flavio Poli 1939/1942.\nH = 21.5 cm.\nRef: Marc Heiremans. SEGUSO VETRI D'ARTE (1932-1973), Arnoldsche, Stuttgart 2014. P. 21, 115 and 247." },
    fr: { hook: "Période 1939-1950 en technique verde mare oro indotto. Conception: Flavio Poli 1939/1942.", desc: "Période 1939-1950 en technique verde mare oro indotto. Conception: Flavio Poli 1939/1942.\nH = 21,5 cm.\nRéf: Marc Heiremans. SEGUSO VETRI D'ARTE (1932-1973), Arnoldsche, Stuttgart 2014. P. 21, 115 et 247." },
    it: { hook: "Periodo 1939-1950 in tecnica verde mare oro indotto. Disegno: Flavio Poli 1939/1942.", desc: "Periodo 1939-1950 in tecnica verde mare oro indotto. Disegno: Flavio Poli 1939/1942.\nA = 21,5 cm.\nBibl: Marc Heiremans. SEGUSO VETRI D'ARTE (1932-1973), Arnoldsche, Stoccarda 2014. P. 21, 115 e 247." }
  },
  93: {
    en: { hook: "Murano circa 1938-1945 in pulegoso verde mare, indotto technique.", desc: "Murano circa 1938-1945 in pulegoso verde mare, indotto technique. Design attributed to Francesco Zecchin / Martinuzzi or Flavio Poli. With remains of the old label.\nH = 22 cm.\nRef: Marc Heiremans. SEGUSO VETRI D'ARTE (1932-1973) Arnoldsche, Stuttgart 2014. P. 58, drawing of an identical vase, however with handles." },
    fr: { hook: "Murano vers 1938-1945 en technique pulegoso verde mare, indotto.", desc: "Murano vers 1938-1945 en technique pulegoso verde mare, indotto. Conception attribuée à Francesco Zecchin / Martinuzzi ou Flavio Poli. Avec restes de l'ancienne étiquette.\nH = 22 cm.\nRéf: Marc Heiremans. SEGUSO VETRI D'ARTE (1932-1973) Arnoldsche, Stuttgart 2014. P. 58, dessin d'un vase identique, cependant avec anses." },
    it: { hook: "Murano circa 1938-1945 in tecnica pulegoso verde mare, indotto.", desc: "Murano circa 1938-1945 in tecnica pulegoso verde mare, indotto. Disegno attribuito a Francesco Zecchin / Martinuzzi o Flavio Poli. Con resti della vecchia etichetta.\nA = 22 cm.\nBibl: Marc Heiremans. SEGUSO VETRI D'ARTE (1932-1973) Arnoldsche, Stoccarda 2014. P. 58, disegno di un vaso identico, tuttavia con manici." }
  },
  94: {
    en: { hook: "Six-arm chandelier, 1930s.", desc: "Six-arm chandelier, 1930s. Signed in the bowl. The design is probably by Napoleone Martinuzzi.\n85 x 57 cm.\nAn early 1930s Venini 6-light chandelier in perfect condition and signed. The design attributed to Napoleone Martinuzzi." },
    fr: { hook: "Lustre à six branches, années 1930.", desc: "Lustre à six branches, années 1930. Signé dans la coupe. La conception est probablement de Napoleone Martinuzzi.\n85 x 57 cm.\nUn lustre Venini 6-lumières du début des années 1930 en parfait état et signé. La conception attribuée à Napoleone Martinuzzi." },
    it: { hook: "Lampadario a sei braccia, anni '30.", desc: "Lampadario a sei braccia, anni '30. Firmato nella coppa. Il disegno è probabilmente di Napoleone Martinuzzi.\n85 x 57 cm.\nUn lampadario Venini a 6 luci dei primi anni '30 in perfette condizioni e firmato. Il disegno attribuito a Napoleone Martinuzzi." }
  },
  95: {
    en: { hook: "Coloured glass in \"tessuto\" technique with brass mount.", desc: "A pair of pendant lamps.\nDesign by Massimo Vignelli (1931-2014) for Venini, Murano circa 1950.\nColoured glass in \"tessuto\" technique with brass mount.\n28 x 18 cm.\nA pair of 1950s pendant lamps in \"tessuto\" technique by Massimo Vignelli (1931-2014) for Venini, Murano.\n11.02 x 7.08 in." },
    fr: { hook: "Verre coloré en technique \"tessuto\" avec monture en laiton.", desc: "Une paire de suspensions.\nConception de Massimo Vignelli (1931-2014) pour Venini, Murano vers 1950.\nVerre coloré en technique \"tessuto\" avec monture en laiton.\n28 x 18 cm.\nUne paire de suspensions des années 1950 en technique \"tessuto\" par Massimo Vignelli (1931-2014) pour Venini, Murano.\n11,02 x 7,08 in." },
    it: { hook: "Vetro colorato in tecnica \"tessuto\" con montatura in ottone.", desc: "Una coppia di sospensioni.\nDisegno di Massimo Vignelli (1931-2014) per Venini, Murano circa 1950.\nVetro colorato in tecnica \"tessuto\" con montatura in ottone.\n28 x 18 cm.\nUna coppia di sospensioni degli anni '50 in tecnica \"tessuto\" di Massimo Vignelli (1931-2014) per Venini, Murano.\n11,02 x 7,08 in." }
  },
  96: {
    en: { hook: "Transparent, blue-tinted glass.", desc: "Vase after a design by Vittorio Zecchin 1921/22. Transparent, blue-tinted glass. Funnel-shaped vase with disc foot. Model number 1463 at Cappellin and 5017 at MVM. Unmarked.\nH = 18 cm. D = 17.5 cm.\nExhibitions: 1922, Paris Salon d'Automne 1923, Monza, 1st Biennale.\nRef: Marino Barovier & Carla Sonego. SKIRA. Vittorio Zecchin, Transparent Glass for Cappellin and Venini." },
    fr: { hook: "Verre transparent teinté bleu.", desc: "Vase d'après un dessin de Vittorio Zecchin 1921/22. Verre transparent teinté bleu. Vase en forme d'entonnoir avec pied en disque. Numéro de modèle 1463 chez Cappellin et 5017 chez MVM. Non signé.\nH = 18 cm. D = 17,5 cm.\nExpositions: 1922, Paris Salon d'Automne 1923, Monza, 1ère Biennale.\nRéf: Marino Barovier & Carla Sonego. SKIRA. Vittorio Zecchin, Transparent Glass for Cappellin and Venini." },
    it: { hook: "Vetro trasparente colorato blu.", desc: "Vaso da un disegno di Vittorio Zecchin 1921/22. Vetro trasparente colorato blu. Vaso a forma di imbuto con piede a disco. Numero di modello 1463 presso Cappellin e 5017 presso MVM. Non contrassegnato.\nA = 18 cm. D = 17,5 cm.\nEsposizioni: 1922, Parigi Salon d'Automne 1923, Monza, 1ª Biennale.\nBibl: Marino Barovier & Carla Sonego. SKIRA. Vittorio Zecchin, Transparent Glass for Cappellin and Venini." }
  },
  97: {
    en: { hook: "Late Classicist table mirror by the Royal Bavarian court gilder Anton Lippert, circa 1900.", desc: "Late Classicist table mirror by the Royal Bavarian court gilder Anton Lippert, circa 1900. In the style of Franz von Stuck. Marked on the base: Radspieler Nachfolger A. Lippert. Kgl. b. Hofvergolder München Hundskugel No. 764.\n76 x 37 x 25 cm." },
    fr: { hook: "Miroir de table néoclassique tardif du doreur royal bavarois Anton Lippert, vers 1900.", desc: "Miroir de table néoclassique tardif du doreur royal bavarois Anton Lippert, vers 1900. Dans le style de Franz von Stuck. Marqué au pied: Radspieler Nachfolger A. Lippert. Kgl. b. Hofvergolder München Hundskugel N° 764.\n76 x 37 x 25 cm." },
    it: { hook: "Specchio da tavolo tardo classicista del doratore reale bavarese Anton Lippert, circa 1900.", desc: "Specchio da tavolo tardo classicista del doratore reale bavarese Anton Lippert, circa 1900. Nello stile di Franz von Stuck. Contrassegnato sulla base: Radspieler Nachfolger A. Lippert. Kgl. b. Hofvergolder München Hundskugel N. 764.\n76 x 37 x 25 cm." }
  },
  98: {
    en: { hook: "Mermaid vase from the Argenta / Celadon series.", desc: "Mermaid vase from the Argenta / Celadon series. Design by Wilhelm Kåge, execution by Gustavsberg, Sweden, 1942.\nSlightly bulbous form with recessed and raised spout.\nThis one with the inscription: \"FRAN * VÄNNERNA * ARVID * CARLANDER * S. E. SIEURIN * 23-9-1942 * SIGURD * THORSTENSON * OCH * HJALMAR * OLSON * J. ARVID * HEDVALL *\".\nOn the base with stamped signature marked HANDDREJAD and GUSTAVSBERG / KÅGE. As well as handwritten inscription CELADON A7.\nStoneware with Celadon glaze and silver overlay.\nH: 29 cm." },
    fr: { hook: "Vase Sirène de la série Argenta / Céladon.", desc: "Vase Sirène de la série Argenta / Céladon. Conception de Wilhelm Kåge, exécution par Gustavsberg, Suède, 1942.\nForme légèrement bombée avec bec rentré et surélevé.\nCelui-ci avec l'inscription: \"FRAN * VÄNNERNA * ARVID * CARLANDER * S. E. SIEURIN * 23-9-1942 * SIGURD * THORSTENSON * OCH * HJALMAR * OLSON * J. ARVID * HEDVALL *\".\nSur le pied avec signature tamponnée marquée HANDDREJAD et GUSTAVSBERG / KÅGE. Ainsi qu'inscription manuscrite CELADON A7.\nGrès avec émail céladon et applique d'argent.\nH: 29 cm." },
    it: { hook: "Vaso Sirena della serie Argenta / Celadon.", desc: "Vaso Sirena della serie Argenta / Celadon. Disegno di Wilhelm Kåge, esecuzione di Gustavsberg, Svezia, 1942.\nForma leggermente bombata con beccuccio rientrante e rialzato.\nQuesto con l'iscrizione: \"FRAN * VÄNNERNA * ARVID * CARLANDER * S. E. SIEURIN * 23-9-1942 * SIGURD * THORSTENSON * OCH * HJALMAR * OLSON * J. ARVID * HEDVALL *\".\nSulla base con firma stampigliata contrassegnata HANDDREJAD e GUSTAVSBERG / KÅGE. Nonché iscrizione a mano CELADON A7.\nGres con smalto celadon e applicazione in argento.\nA: 29 cm." }
  },
  99: {
    en: { hook: "Sculptural decorative lamp by Willy Daro, Brussels, Belgium, circa 1970.", desc: "Sculptural decorative lamp by Willy Daro, Brussels, Belgium, circa 1970. Agate and brass.\n30 x 28 x 9 cm." },
    fr: { hook: "Lampe décorative sculpturale de Willy Daro, Bruxelles, Belgique, vers 1970.", desc: "Lampe décorative sculpturale de Willy Daro, Bruxelles, Belgique, vers 1970. Agate et laiton.\n30 x 28 x 9 cm." },
    it: { hook: "Lampada decorativa scultorea di Willy Daro, Bruxelles, Belgio, circa 1970.", desc: "Lampada decorativa scultorea di Willy Daro, Bruxelles, Belgio, circa 1970. Agata e ottone.\n30 x 28 x 9 cm." }
  },
  100: {
    en: { hook: "Venini. Design: Paolo Venini 1956.", desc: "Venini. Design: Paolo Venini 1956. One base is signed with diamond point signature: Venini Italia. H = 52 cm each." },
    fr: { hook: "Venini. Conception: Paolo Venini 1956.", desc: "Venini. Conception: Paolo Venini 1956. Un pied est signé à la pointe de diamant: Venini Italia. H = 52 cm chacun." },
    it: { hook: "Venini. Disegno: Paolo Venini 1956.", desc: "Venini. Disegno: Paolo Venini 1956. Una base è firmata a punta di diamante: Venini Italia. A = 52 cm ciascuna." }
  }
});
